// Scenarios and writer of the two execution-replay goldens — shared by the
// generator (make_replay_fills_golden.cpp) and by
// tests/test_replay_fills_passive.cpp, which renders both documents in
// memory and compares them with the committed files byte for byte.
//
//   tests/golden/expected_replay_fills.json          (x-version 2, NATIVE)
//     parent 1: VWAP BUY 400 over [t0+60s, t0+660s), 4 slices, passive LIMIT
//               children joining the best bid at each slice decision;
//     parent 2: IS   SELL 600 over [t0+120s, t0+720s), 3 slices,
//               risk_aversion 1.0, aggressive MARKET children.
//   tests/golden/expected_replay_fills_passive.json  (x-version 1, policies)
//     parent 1: VWAP BUY  400, same window and slices, PASSIVE, urgency 0.5;
//     parent 2: IS   SELL 600, same window and slices, PASSIVE, urgency 0.2;
//     parent 3: POV  BUY  300 over [t0+90s, t0+690s), participation 0.1,
//               PASSIVE, urgency 0.0, SOR-routed (venue_id 0);
//     parent 4: TWAP SELL 200 over [t0+150s, t0+450s), 4 slices, AGGRESSIVE.
//
// Config of both: seed 20260829, latency decision/risk/wire 50/50/100 us +
// XV1 venue latency (mean 150 us, jitter uniform [0, 50 us], SplitMix64),
// impact_coeff_bps_per_pct_adv 2.0, instrument 1 adv 38,000,000 lot 1.0
// (fees per share); PASSIVE parameters = the PassiveParams defaults. The
// fill list is exact (ticks/qty/ts); fee and impact_cost are doubles
// printed with %.17g (round-trip exact). The policy golden is committed
// from python/tools/make_golden_replay_passive.py, which writes the same
// bytes.

#pragma once

#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

#include "iap/replay/exec_replay.hpp"

namespace iap_golden {

inline const char* const kNativeDescription =
    "Execution-replay golden fills: events_eq_mbo.jsonl "
    "(instrument 1, venue XV1, tick 0.01) worked by parent 1 = "
    "VWAP BUY 400 over [t0+60s, t0+660s) in 4 passive LIMIT "
    "slices joining the best bid, and parent 2 = IS SELL 600 over "
    "[t0+120s, t0+720s) in 3 front-loaded MARKET slices "
    "(risk_aversion 1.0). Pinned rules: "
    "cpp/include/iap/execution/execution.hpp and algos.hpp (C++ "
    "port is the reference; v2: children expire at the parent "
    "end_ts, no fill outlives the window, displayed liquidity "
    "consumed by an earlier child is not re-used). Latency "
    "decision/risk/wire 50000/50000/100000 ns + venue mean 150000 "
    "ns + SplitMix64(seed).below(jitter+1) per submission. "
    "ticks/qty/ts exact; fee/impact_cost at 1e-9.";

inline const char* const kPassiveDescription =
    "Execution-policy golden fills: events_eq_mbo.jsonl "
    "(instrument 1, venue XV1, tick 0.01) worked by parent 1 = "
    "VWAP BUY 400 over [t0+60s, t0+660s) in 4 slices under the "
    "PASSIVE policy (urgency 0.5), parent 2 = IS SELL 600 over "
    "[t0+120s, t0+720s) in 3 slices (risk_aversion 1.0) under "
    "PASSIVE (urgency 0.2), parent 3 = POV BUY 300 over [t0+90s, "
    "t0+690s) at participation 0.1 under PASSIVE (urgency 0.0), "
    "SOR-routed, and parent 4 = TWAP SELL 200 over [t0+150s, "
    "t0+450s) in 4 slices under AGGRESSIVE. PASSIVE = POST at the "
    "near touch (one tick inside when the spread is >= 3 ticks, "
    "never at or through the opposite touch) -> REST for "
    "floor(30e9 * (1 - urgency) * (exp(-risk_aversion) for IS)) "
    "ns or until the schedule is more than floor(0.1 * qty) "
    "behind -> REPRICE once -> CROSS (MARKET); pinned rules: "
    "cpp/include/iap/execution/algos.hpp. Simulator configuration "
    "of expected_replay_fills.json (seed 20260829). Generated by "
    "python/tools/make_golden_replay_passive.py, byte-identical "
    "to cpp/tools/make_replay_fills_golden.cpp in passive mode. "
    "ticks/qty/ts and the transition counters exact; "
    "fee/impact_cost at 1e-9.";

inline iap::ExecConfig golden_exec_config(const std::string& configs_dir) {
    iap::ExecConfig cfg;
    cfg.seed = 20260829;
    cfg.impact_coeff_bps_per_pct_adv = 2.0;
    cfg.venues = iap::load_venues(configs_dir + "/venues/venues.json");
    iap::InstrumentSpec ins;
    ins.instrument_id = 1;
    ins.tick_size = 0.01;
    ins.qty_unit = 1.0;
    ins.adv = 38000000.0;
    cfg.instruments[1] = ins;
    return cfg;
}

inline iap::ParentOrder golden_parent(std::uint64_t parent_id,
                                      std::uint16_t venue_id, std::uint8_t side,
                                      std::int64_t qty, iap::AlgoType algo,
                                      std::int64_t start_ts, std::int64_t end_ts) {
    iap::ParentOrder p;
    p.parent_id = parent_id;
    p.instrument_id = 1;
    p.venue_id = venue_id;
    p.side = side;
    p.qty = qty;
    p.algo = algo;
    p.start_ts = start_ts;
    p.end_ts = end_ts;
    return p;
}

inline std::vector<iap::ParentOrder> native_parents(std::int64_t t0) {
    constexpr std::int64_t kSec = 1'000'000'000;
    iap::ParentOrder vwap = golden_parent(1, 1, 0, 400, iap::AlgoType::VWAP,
                                          t0 + 60 * kSec, t0 + 660 * kSec);
    vwap.slices = 4;
    iap::ParentOrder is = golden_parent(2, 1, 1, 600, iap::AlgoType::IS,
                                        t0 + 120 * kSec, t0 + 720 * kSec);
    is.slices = 3;
    is.risk_aversion = 1.0;
    return {vwap, is};
}

inline std::vector<iap::ParentOrder> passive_parents(std::int64_t t0) {
    constexpr std::int64_t kSec = 1'000'000'000;
    iap::ParentOrder vwap = golden_parent(1, 1, 0, 400, iap::AlgoType::VWAP,
                                          t0 + 60 * kSec, t0 + 660 * kSec);
    vwap.slices = 4;
    vwap.policy = iap::ExecPolicy::PASSIVE;
    vwap.urgency = 0.5;
    iap::ParentOrder is = golden_parent(2, 1, 1, 600, iap::AlgoType::IS,
                                        t0 + 120 * kSec, t0 + 720 * kSec);
    is.slices = 3;
    is.risk_aversion = 1.0;
    is.policy = iap::ExecPolicy::PASSIVE;
    is.urgency = 0.2;
    iap::ParentOrder pov = golden_parent(3, 0, 0, 300, iap::AlgoType::POV,
                                         t0 + 90 * kSec, t0 + 690 * kSec);
    pov.participation = 0.1;
    pov.policy = iap::ExecPolicy::PASSIVE;
    pov.urgency = 0.0;
    iap::ParentOrder twap = golden_parent(4, 1, 1, 200, iap::AlgoType::TWAP,
                                          t0 + 150 * kSec, t0 + 450 * kSec);
    twap.slices = 4;
    twap.policy = iap::ExecPolicy::AGGRESSIVE;
    return {vwap, is, pov, twap};
}

// printf("%.17g") of a double (round-trip exact).
inline std::string g17(double x) {
    char buf[64];
    std::snprintf(buf, sizeof(buf), "%.17g", x);
    return std::string(buf);
}

// The golden document. `with_passive` appends the PASSIVE transition
// counters (policy golden only; the NATIVE golden has no such block).
inline std::string render_replay_fills(const iap::ExecReplayResult& res,
                                       std::int64_t t0, int x_version,
                                       const std::string& description,
                                       bool with_passive) {
    using std::to_string;
    std::string out = "{\n  \"x-version\": " + to_string(x_version) + ",\n";
    out += "  \"description\": \"" + description + "\",\n";
    out += "  \"seed\": 20260829,\n";
    out += "  \"t0\": " + to_string(t0) + ",\n";
    out += "  \"events_processed\": " + to_string(res.events_processed) + ",\n";
    out += "  \"fills\": [\n";
    for (std::size_t i = 0; i < res.fills.size(); ++i) {
        const iap::Fill& x = res.fills[i];
        out += "    {\"fill_id\": " + to_string(x.fill_id);
        out += ", \"order_id\": " + to_string(x.order_id);
        out += ", \"parent_id\": " + to_string(x.parent_id);
        out += ", \"instrument_id\": " + to_string(x.instrument_id);
        out += ", \"venue_id\": " + to_string(static_cast<unsigned>(x.venue_id));
        out += ", \"side\": " + to_string(static_cast<unsigned>(x.side));
        out += ", \"price_ticks\": " + to_string(x.price_ticks);
        out += ", \"qty\": " + to_string(x.qty);
        out += ", \"ts\": " + to_string(x.ts);
        out += ", \"liquidity\": \"";
        out += x.liquidity == iap::Liquidity::MAKER ? "MAKER" : "TAKER";
        out += "\", \"fee\": " + g17(x.fee);
        out += ", \"impact_cost\": " + g17(x.impact_cost) + "}";
        out += i + 1 < res.fills.size() ? ",\n" : "\n";
    }
    out += "  ],\n  \"parents\": {\n";
    std::size_t np = 0;
    for (const auto& [pid, r] : res.parents) {
        out += "    \"" + to_string(pid) + "\": {\"filled_qty\": " +
               to_string(r.filled_qty);
        out += ", \"unfilled_qty\": " + to_string(r.unfilled_qty);
        out += ", \"children\": " + to_string(r.children);
        out += ", \"notional\": " + g17(r.notional);
        out += ", \"avg_price\": " + g17(r.avg_price);
        out += ", \"fees\": " + g17(r.fees);
        out += ", \"rebates\": " + g17(r.rebates);
        out += ", \"impact\": " + g17(r.impact);
        out += ", \"total_cost\": " + g17(r.total_cost) + "}";
        out += ++np < res.parents.size() ? ",\n" : "\n";
    }
    if (!with_passive) {
        out += "  }\n}\n";
        return out;
    }
    out += "  },\n  \"passive\": {\n";
    std::size_t ns = 0;
    for (const auto& [pid, s] : res.passive) {
        out += "    \"" + to_string(pid) + "\": {\"posts\": " + to_string(s.posts);
        out += ", \"reprices\": " + to_string(s.reprices);
        out += ", \"rest_extensions\": " + to_string(s.rest_extensions);
        out += ", \"crosses_timeout\": " + to_string(s.crosses_timeout);
        out += ", \"crosses_behind\": " + to_string(s.crosses_behind);
        out += ", \"crosses_immediate\": " + to_string(s.crosses_immediate) + "}";
        out += ++ns < res.passive.size() ? ",\n" : "\n";
    }
    out += "  }\n}\n";
    return out;
}

}  // namespace iap_golden
