//! Replay of the risk differential-fuzz corpus (`tests/golden/risk_fuzz/`,
//! generated by `python/tools/make_risk_fuzz_corpus.py`; format and
//! generator: `python/tools/risk_fuzz.py`) — the Rust side of the
//! three-language parity proof (Java `RiskFuzzGoldenTest`, Python
//! `python/tests/test_risk_fuzz_golden.py`).
//!
//! Every script is replayed through the engine: each order step's decision,
//! rule, severity, scope, scope id and reason must match, the audit JSONL and
//! the final snapshot must be byte-identical, and at every cut point a
//! snapshot -> JSON text -> restore -> continue run must produce exactly the
//! unbroken run's remaining audit lines and final state.
//!
//! Two environment variables turn the same test into the nightly job's
//! engine driver (`python/tools/risk_fuzz_nightly.py`):
//! `IAP_RISK_FUZZ_DIR` replays that directory instead of the committed
//! corpus, and `IAP_RISK_FUZZ_OUT` makes the test REPORT instead of fail —
//! it writes `rust.tsv` (`name<TAB>OK` or `name<TAB>DIVERGED<TAB>why` per
//! script), `<name>.rust.audit.jsonl` and `<name>.rust.snapshot.json` (the
//! audit and final state actually produced) there.
//!
//! NaN and Infinity cannot be carried in JSON, so no script contains them;
//! `non_finite_inputs_are_rejected_like_the_other_ports` pins those inputs.

use std::collections::BTreeMap;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::path::{Path, PathBuf};

use risk::{rules, Fill, InstrumentRef, RiskEngine, RiskLimits, Scope};
use serde_json::Value;
use venue::OrderRequest;

fn repo_path(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..").join(rel)
}

fn env_dir(name: &str) -> Option<PathBuf> {
    std::env::var(name).ok().filter(|v| !v.is_empty()).map(PathBuf::from)
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

struct Case {
    name: String,
    script: Value,
    audit: String,
    snapshot: String,
}

/// Every script of a corpus directory, by file name.
fn load_corpus(dir: &Path) -> Vec<Case> {
    let mut names: Vec<String> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("listing {}: {e}", dir.display()))
        .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
        .filter_map(|n| n.strip_suffix(".json").map(str::to_string))
        .filter(|stem| !stem.ends_with(".snapshot"))
        .collect();
    names.sort();
    names
        .into_iter()
        .map(|name| {
            let text = read(&dir.join(format!("{name}.json")));
            let script = serde_json::from_str(&text)
                .unwrap_or_else(|e| panic!("parsing {name}.json: {e}"));
            Case {
                audit: read(&dir.join(format!("{name}.audit.jsonl"))),
                snapshot: read(&dir.join(format!("{name}.snapshot.json"))),
                script,
                name,
            }
        })
        .collect()
}

fn parse_scope(s: &str) -> Scope {
    match s {
        "GLOBAL" => Scope::Global,
        "STRATEGY" => Scope::Strategy,
        "INSTRUMENT" => Scope::Instrument,
        "VENUE" => Scope::Venue,
        other => panic!("bad scope {other}"),
    }
}

fn scope_name(scope: Scope) -> &'static str {
    match scope {
        Scope::Global => "GLOBAL",
        Scope::Strategy => "STRATEGY",
        Scope::Instrument => "INSTRUMENT",
        Scope::Venue => "VENUE",
    }
}

fn parse_order(v: &Value) -> OrderRequest {
    OrderRequest {
        order_id: v["order_id"].as_u64().unwrap(),
        instrument_id: v["instrument_id"].as_u64().unwrap() as u32,
        side: v["side"].as_u64().unwrap() as u8,
        qty: v["qty"].as_i64().unwrap(),
        price_ticks: v["price_ticks"].as_i64().unwrap(),
        order_type: v["order_type"].as_u64().unwrap() as u8,
        venue_id: v["venue_id"].as_u64().unwrap() as u16,
        strategy_id: v["strategy_id"].as_str().unwrap().to_string(),
        urgency: v["urgency"].as_f64().unwrap(),
        timestamp: v["timestamp"].as_i64().unwrap(),
    }
}

fn parse_fill(v: &Value) -> Fill {
    Fill {
        ts: v["ts"].as_i64().unwrap(),
        strategy_id: v["strategy_id"].as_str().unwrap().to_string(),
        instrument_id: v["instrument_id"].as_u64().unwrap() as u32,
        order_id: v["order_id"].as_u64().unwrap(),
        side: v["side"].as_u64().unwrap() as u8,
        qty: v["qty"].as_i64().unwrap(),
        price_ticks: v["price_ticks"].as_i64().unwrap(),
    }
}

fn instruments(script: &Value) -> BTreeMap<u32, InstrumentRef> {
    let mut out = BTreeMap::new();
    for (iid, spec) in script["instruments"].as_object().unwrap() {
        out.insert(
            iid.parse::<u32>().unwrap(),
            InstrumentRef::new(
                spec["tick_size"].as_f64().unwrap(),
                spec["qty_unit"].as_f64().unwrap(),
                spec["quote_ccy"].as_str().unwrap(),
            ),
        );
    }
    out
}

/// The committed config with the script's `config_remove` / `config_set`.
fn effective_config(script: &Value) -> Value {
    let mut doc: Value =
        serde_json::from_str(&read(&repo_path(script["config"].as_str().unwrap()))).unwrap();
    if let Some(rm) = script["config_remove"].as_array() {
        let section = rm[0].as_str().unwrap();
        if rm.len() == 1 {
            doc.as_object_mut().unwrap().remove(section);
        } else {
            doc[section].as_object_mut().unwrap().remove(rm[1].as_str().unwrap());
        }
    }
    if let Some(sets) = script["config_set"].as_array() {
        for set in sets {
            doc[set[0].as_str().unwrap()][set[1].as_str().unwrap()] = set[2].clone();
        }
    }
    doc
}

/// One replay of a script; `done` holds the audit of engines already
/// replaced by a restore.
struct Runner {
    doc: Value,
    refs: BTreeMap<u32, InstrumentRef>,
    eng: RiskEngine,
    done: String,
    done_lines: usize,
}

impl Runner {
    fn new(script: &Value) -> Runner {
        let doc = effective_config(script);
        let refs = instruments(script);
        let mut eng = RiskEngine::from_config(&doc, refs.clone());
        if script["require_bootstrap"].as_bool() == Some(true) {
            eng.require_bootstrap();
        }
        Runner { doc, refs, eng, done: String::new(), done_lines: 0 }
    }

    fn line_count(&self) -> usize {
        self.done_lines + self.eng.audit().len()
    }

    fn audit(&self) -> String {
        format!("{}{}", self.done, self.eng.audit_jsonl())
    }

    /// Final snapshot, compact `serde_json` layout plus a newline; empty for
    /// a fail-closed configuration (it cannot be restored).
    fn snapshot_text(&self) -> String {
        if RiskLimits::from_json(&self.doc).is_err() {
            return String::new();
        }
        format!("{}\n", self.eng.snapshot())
    }

    /// Snapshot through the JSON text and continue on the restored engine.
    fn restore(&mut self, ts: i64) -> Result<(), String> {
        self.done.push_str(&self.eng.audit_jsonl());
        self.done_lines += self.eng.audit().len();
        let text = self.eng.snapshot().to_string();
        let snap: Value = serde_json::from_str(&text).map_err(|e| format!("snapshot text: {e}"))?;
        let limits = RiskLimits::from_json(&self.doc).map_err(|e| format!("limits: {e}"))?;
        self.eng = RiskEngine::restore(limits, self.refs.clone(), &snap, ts)
            .map_err(|e| format!("restore: {e}"))?;
        Ok(())
    }

    /// Apply step `i`; with `check`, compare it with the recorded expectation.
    fn apply(&mut self, i: usize, step: &Value, check: bool) -> Result<(), String> {
        let ts = || step["ts"].as_i64().unwrap();
        let iid = || step["instrument_id"].as_u64().unwrap() as u32;
        let venue = || step["venue_id"].as_u64().unwrap() as u16;
        let scope = || parse_scope(step["scope"].as_str().unwrap());
        let scope_id = || step["scope_id"].as_str().unwrap();
        let reason = || step["reason"].as_str().unwrap_or("");
        let kind = step["type"].as_str().unwrap();
        match kind {
            "order" => {
                let order = parse_order(&step["order"]);
                let d = self.eng.check_order(&order);
                if check {
                    let ev = self.eng.audit().last().expect("a decision is always audited");
                    let exp = &step["expect"];
                    let got = (
                        d.decision as u64,
                        d.rule_id.as_str(),
                        d.severity as u64,
                        scope_name(ev.scope),
                        ev.scope_id.as_str(),
                        d.reason.as_str(),
                    );
                    let want = (
                        exp["decision"].as_u64().unwrap(),
                        exp["rule_id"].as_str().unwrap(),
                        exp["severity"].as_u64().unwrap(),
                        exp["scope"].as_str().unwrap(),
                        exp["scope_id"].as_str().unwrap(),
                        exp["reason"].as_str().unwrap(),
                    );
                    if got != want {
                        return Err(format!(
                            "step {i} order {}: got {got:?}, want {want:?}",
                            order.order_id
                        ));
                    }
                }
            }
            "market" => self.eng.on_market(
                iid(),
                step["bid_ticks"].as_i64().unwrap(),
                step["ask_ticks"].as_i64().unwrap(),
                ts(),
            ),
            "fill" => {
                self.eng.on_fill(&parse_fill(step));
            }
            "cancel" => self.eng.on_order_done(step["order_id"].as_u64().unwrap()),
            "gap" => self.eng.on_sequence_gap(iid(), ts()),
            "recover" => self.eng.on_feed_recovered(iid(), ts()),
            "venue_down" => self.eng.on_venue_disconnect(venue(), ts()),
            "venue_up" => self.eng.on_venue_reconnect(venue(), ts()),
            "kill" | "bad_kill" | "unkill" | "bad_unkill" | "override_loss" | "bad_override" => {
                let failed = match kind {
                    "kill" | "bad_kill" => {
                        self.eng.engage_kill(scope(), scope_id(), ts(), reason()).is_err()
                    }
                    "unkill" | "bad_unkill" => {
                        self.eng.clear_kill(scope(), scope_id(), ts(), reason()).is_err()
                    }
                    _ => self
                        .eng
                        .override_loss_limit(
                            scope(),
                            scope_id(),
                            step["new_limit"].as_f64().unwrap(),
                            ts(),
                            step["approver"].as_str().unwrap_or(""),
                        )
                        .is_err(),
                };
                if check && failed != kind.starts_with("bad_") {
                    let outcome = if failed { "failed" } else { "succeeded" };
                    return Err(format!("step {i} {kind}: the call {outcome}"));
                }
            }
            "roll_session" => self.eng.roll_session(ts(), reason()),
            "bootstrap" => {
                let fills: Vec<Fill> =
                    step["fills"].as_array().unwrap().iter().map(parse_fill).collect();
                self.eng.bootstrap_positions(&fills, ts());
            }
            "restore" => self.restore(ts())?,
            other => return Err(format!("step {i}: unknown step type {other}")),
        }
        Ok(())
    }
}

/// Replay once. With `cut` the engine is snapshotted and restored (`ts` 0)
/// after that step. Returns `(audit, lines emitted up to the cut, snapshot)`.
fn run(script: &Value, cut: Option<usize>, check: bool) -> Result<(String, usize, String), String> {
    let mut runner = Runner::new(script);
    let mut mark = 0;
    for (i, step) in script["steps"].as_array().unwrap().iter().enumerate() {
        runner.apply(i, step, check)?;
        if cut == Some(i) {
            mark = runner.line_count();
            runner.restore(0)?;
        }
    }
    Ok((runner.audit(), mark, runner.snapshot_text()))
}

fn first_diff(got: &[&str], want: &[&str]) -> String {
    for (i, (a, b)) in got.iter().zip(want).enumerate() {
        if a != b {
            return format!("line {i}: got {a} want {b}");
        }
    }
    format!("{} lines, want {}", got.len(), want.len())
}

/// The audit's lines (LF only: a reason may contain U+2028 or a lone CR
/// escape, never a raw line feed).
fn lines(audit: &str) -> Vec<&str> {
    let mut out: Vec<&str> = audit.split('\n').collect();
    out.pop();
    out
}

/// The full check of one script.
fn verify(case: &Case) -> Result<(), String> {
    let (audit, _, snapshot) = run(&case.script, None, true)?;
    let full = lines(&audit);
    if audit != case.audit {
        return Err(format!("audit differs: {}", first_diff(&full, &lines(&case.audit))));
    }
    if snapshot != case.snapshot {
        return Err("final snapshot differs".to_string());
    }
    for cut in case.script["cuts"].as_array().unwrap() {
        let cut = cut.as_u64().unwrap() as usize;
        let (got, mark, snap) = run(&case.script, Some(cut), true)?;
        let got = lines(&got);
        if !got[mark].contains("\"rule_id\":\"STATE_RESTORED\"") {
            return Err(format!("cut {cut}: no STATE_RESTORED record"));
        }
        if got[..mark] != full[..mark] || got[mark + 1..] != full[mark..] {
            return Err(format!("cut {cut}: the restored engine's audit tail differs"));
        }
        if snap != case.snapshot {
            return Err(format!("cut {cut}: the restored engine's final state differs"));
        }
    }
    Ok(())
}

/// `verify`, with a panic (an unchecked overflow, an index out of range)
/// turned into a reported divergence.
fn verdict(case: &Case) -> Result<(), String> {
    match catch_unwind(AssertUnwindSafe(|| verify(case))) {
        Ok(result) => result,
        Err(payload) => {
            let why = payload
                .downcast_ref::<String>()
                .map(String::as_str)
                .or_else(|| payload.downcast_ref::<&str>().copied())
                .unwrap_or("panic");
            Err(format!("panicked: {why}"))
        }
    }
}

fn one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ").chars().take(2000).collect()
}

#[test]
fn fuzz_corpus_replays_byte_for_byte() {
    let external = env_dir("IAP_RISK_FUZZ_DIR");
    let dir = external.clone().unwrap_or_else(|| repo_path("tests/golden/risk_fuzz"));
    let corpus = load_corpus(&dir);
    if external.is_none() {
        let steps: usize =
            corpus.iter().map(|c| c.script["steps"].as_array().unwrap().len()).sum();
        assert!(corpus.len() >= 36, "the committed corpus has {} scripts", corpus.len());
        assert!(steps >= 3000, "the committed corpus has {steps} steps");
    }
    let verdicts: Vec<(&Case, Result<(), String>)> =
        corpus.iter().map(|case| (case, verdict(case))).collect();
    if let Some(out) = env_dir("IAP_RISK_FUZZ_OUT") {
        std::fs::create_dir_all(&out).unwrap();
        let mut report = String::new();
        for (case, result) in &verdicts {
            match result {
                Ok(()) => report.push_str(&format!("{}\tOK\n", case.name)),
                Err(why) => {
                    report.push_str(&format!("{}\tDIVERGED\t{}\n", case.name, one_line(why)))
                }
            }
            let (audit, _, state) =
                catch_unwind(AssertUnwindSafe(|| run(&case.script, None, false)))
                    .ok()
                    .and_then(Result::ok)
                    .unwrap_or_default();
            std::fs::write(out.join(format!("{}.rust.audit.jsonl", case.name)), audit).unwrap();
            std::fs::write(out.join(format!("{}.rust.snapshot.json", case.name)), state).unwrap();
        }
        std::fs::write(out.join("rust.tsv"), report).unwrap();
        return;
    }
    let failures: Vec<String> = verdicts
        .iter()
        .filter_map(|(case, result)| result.as_ref().err().map(|why| format!("{}: {why}", case.name)))
        .collect();
    assert!(
        failures.is_empty(),
        "{} of {} fuzz scripts diverge from the oracle:\n{}",
        failures.len(),
        corpus.len(),
        failures.join("\n")
    );
}

/// A snapshot with any field missing or of the wrong type is refused (the
/// one optional field is `loss_override_global`: absent means no override);
/// a truncated document does not even parse.
#[test]
fn fuzz_corpus_corrupt_snapshots_fail_closed() {
    let corpus = load_corpus(&repo_path("tests/golden/risk_fuzz"));
    let mut checked = 0;
    for case in corpus.iter().filter(|c| !c.snapshot.is_empty()) {
        let doc = effective_config(&case.script);
        let limits = || RiskLimits::from_json(&doc).unwrap();
        let refs = instruments(&case.script);
        let snap: Value = serde_json::from_str(&case.snapshot).unwrap();
        assert!(RiskEngine::restore(limits(), refs.clone(), &snap, 0).is_ok(), "{}", case.name);
        for key in snap.as_object().unwrap().keys() {
            let mut wrong = snap.clone();
            wrong[key.as_str()] = Value::String("x".to_string());
            assert!(
                RiskEngine::restore(limits(), refs.clone(), &wrong, 0).is_err(),
                "{}: {key} of the wrong type must be refused",
                case.name
            );
            if key != "loss_override_global" {
                let mut missing = snap.clone();
                missing.as_object_mut().unwrap().remove(key);
                assert!(
                    RiskEngine::restore(limits(), refs.clone(), &missing, 0).is_err(),
                    "{}: a snapshot without {key} must be refused",
                    case.name
                );
            }
            checked += 1;
        }
        let half = &case.snapshot[..case.snapshot.len() / 2];
        assert!(serde_json::from_str::<Value>(half).is_err(), "{}", case.name);
    }
    assert!(checked >= 30 * 16, "{checked} snapshot fields checked");
}

/// NaN / Infinity never reach the JSON corpus; pin them here. The same
/// assertions live in the Java and Python fuzz tests.
#[test]
fn non_finite_inputs_are_rejected_like_the_other_ports() {
    const T0: i64 = 1_700_000_000_000_000_000;
    let doc: Value = serde_json::from_str(&read(&repo_path("configs/risk/risk.json"))).unwrap();
    let mut refs = BTreeMap::new();
    refs.insert(1u32, InstrumentRef::equity(0.01));
    let mut eng = RiskEngine::from_config(&doc, refs);
    eng.on_market(1, 2450, 2452, T0);
    let order = |order_id: u64, urgency: f64| OrderRequest {
        order_id,
        instrument_id: 1,
        side: 0,
        qty: 10,
        price_ticks: 2450,
        order_type: 2,
        venue_id: 1,
        strategy_id: "S1".to_string(),
        urgency,
        timestamp: T0,
    };
    let cases = [(f64::NAN, "NaN"), (f64::INFINITY, "inf"), (f64::NEG_INFINITY, "-inf")];
    for (k, (urgency, text)) in cases.iter().enumerate() {
        let d = eng.check_order(&order(k as u64 + 1, *urgency));
        assert_eq!(d.rule_id, rules::MALFORMED_ORDER);
        assert_eq!(d.reason, format!("urgency must be in [0, 1]: {text}"));
    }
    for (scope, scope_id) in [(Scope::Global, ""), (Scope::Strategy, "S1")] {
        for (bad, _) in cases {
            assert!(eng.override_loss_limit(scope, scope_id, bad, T0, "ops").is_err());
        }
    }
    assert_eq!(eng.audit().len(), 3, "a refused override leaves no audit record");
    assert_eq!(eng.check_order(&order(9, 0.5)).rule_id, rules::ALLOW);
}
