#!/usr/bin/env python3
"""Generate tests/golden/expected_replay_fills_passive.json (x-version 1).

The execution-policy golden: the EQ golden vector (events_eq_mbo.jsonl,
instrument 1, venue XV1, tick 0.01) worked by four parent orders under the
non-default execution policies (iap.execution.passive):

  parent 1: VWAP BUY  400 over [t0+60s,  t0+660s), 4 slices, PASSIVE,
            urgency 0.5 (rest 15 s per post);
  parent 2: IS   SELL 600 over [t0+120s, t0+720s), 3 slices, risk_aversion
            1.0, PASSIVE, urgency 0.2 (rest floor(30e9 * 0.8 * e^-1) ns);
  parent 3: POV  BUY  300 over [t0+90s,  t0+690s), participation 0.1,
            PASSIVE, urgency 0.0 (rest 30 s), SOR-routed (venue_id 0);
  parent 4: TWAP SELL 200 over [t0+150s, t0+450s), 4 slices, AGGRESSIVE
            (MARKET children).

PASSIVE parameters are the PassiveParams defaults (max_rest_ns 30 s,
max_reprices 1, max_behind_fraction 0.1, improve_min_spread_ticks 3,
end_margin_ns 1 s); the simulator configuration is the one of
expected_replay_fills.json (seed 20260829, impact 2.0 bps per %ADV).

The file is written by this Python port in exactly the bytes the C++
reference generator (cpp/tools/make_replay_fills_golden.cpp, mode
`passive`) writes — the C++ test
ReplayFillsPassiveGolden.GeneratorReproducesBothFilesByteForByte renders the
document with that generator's writer and compares it with the committed
file byte for byte, and the C++, Java and Python golden tests reproduce
every fill.

Usage: PYTHONPATH=src python3 tools/make_golden_replay_passive.py [--force]
"""

from __future__ import annotations

import sys
from pathlib import Path

from iap.core.codec import read_jsonl
from iap.execution import (
    AlgoType,
    ExecConfig,
    ExecPolicy,
    ExecReplayResult,
    ExecutionReplay,
    InstrumentSpec,
    ParentOrder,
    load_venues,
)

REPO = Path(__file__).resolve().parents[2]
GOLDEN = REPO / "tests" / "golden" / "expected_replay_fills_passive.json"
SEC = 1_000_000_000

DESCRIPTION = (
    "Execution-policy golden fills: events_eq_mbo.jsonl (instrument 1, venue "
    "XV1, tick 0.01) worked by parent 1 = VWAP BUY 400 over [t0+60s, t0+660s) "
    "in 4 slices under the PASSIVE policy (urgency 0.5), parent 2 = IS SELL "
    "600 over [t0+120s, t0+720s) in 3 slices (risk_aversion 1.0) under PASSIVE "
    "(urgency 0.2), parent 3 = POV BUY 300 over [t0+90s, t0+690s) at "
    "participation 0.1 under PASSIVE (urgency 0.0), SOR-routed, and parent 4 "
    "= TWAP SELL 200 over [t0+150s, t0+450s) in 4 slices under AGGRESSIVE. "
    "PASSIVE = POST at the near touch (one tick inside when the spread is >= "
    "3 ticks, never at or through the opposite touch) -> REST for "
    "floor(30e9 * (1 - urgency) * (exp(-risk_aversion) for IS)) ns or until "
    "the schedule is more than floor(0.1 * qty) behind -> REPRICE once -> "
    "CROSS (MARKET); pinned rules: cpp/include/iap/execution/algos.hpp. "
    "Simulator configuration of expected_replay_fills.json (seed 20260829). "
    "Generated by python/tools/make_golden_replay_passive.py, byte-identical "
    "to cpp/tools/make_replay_fills_golden.cpp in passive mode. ticks/qty/ts "
    "and the transition counters exact; fee/impact_cost at 1e-9."
)


def golden_config(configs_dir: Path) -> ExecConfig:
    """The simulator configuration of both replay-fills goldens."""
    return ExecConfig(
        seed=20260829,
        impact_coeff_bps_per_pct_adv=2.0,
        venues=load_venues(configs_dir / "venues" / "venues.json"),
        instruments={1: InstrumentSpec(1, 0.01, 1.0, 38_000_000.0)},
    )


def golden_parents(t0: int) -> list[ParentOrder]:
    """The four pinned parents (module docstring)."""
    return [
        ParentOrder(
            parent_id=1,
            instrument_id=1,
            venue_id=1,
            side=0,
            qty=400,
            algo=AlgoType.VWAP,
            start_ts=t0 + 60 * SEC,
            end_ts=t0 + 660 * SEC,
            slices=4,
            policy=ExecPolicy.PASSIVE,
            urgency=0.5,
        ),
        ParentOrder(
            parent_id=2,
            instrument_id=1,
            venue_id=1,
            side=1,
            qty=600,
            algo=AlgoType.IS,
            start_ts=t0 + 120 * SEC,
            end_ts=t0 + 720 * SEC,
            slices=3,
            risk_aversion=1.0,
            policy=ExecPolicy.PASSIVE,
            urgency=0.2,
        ),
        ParentOrder(
            parent_id=3,
            instrument_id=1,
            venue_id=0,
            side=0,
            qty=300,
            algo=AlgoType.POV,
            start_ts=t0 + 90 * SEC,
            end_ts=t0 + 690 * SEC,
            participation=0.1,
            policy=ExecPolicy.PASSIVE,
            urgency=0.0,
        ),
        ParentOrder(
            parent_id=4,
            instrument_id=1,
            venue_id=1,
            side=1,
            qty=200,
            algo=AlgoType.TWAP,
            start_ts=t0 + 150 * SEC,
            end_ts=t0 + 450 * SEC,
            slices=4,
            policy=ExecPolicy.AGGRESSIVE,
        ),
    ]


def _g17(x: float) -> str:
    """C ``printf("%.17g")`` (round-trip exact)."""
    return format(x, ".17g")


def render(res: ExecReplayResult, t0: int) -> str:
    """The golden document, byte for byte as the C++ generator prints it."""
    out = ['{\n  "x-version": 1,\n']
    out.append(f'  "description": "{DESCRIPTION}",\n')
    out.append('  "seed": 20260829,\n')
    out.append(f'  "t0": {t0},\n')
    out.append(f'  "events_processed": {res.events_processed},\n')
    out.append('  "fills": [\n')
    for i, x in enumerate(res.fills):
        out.append(
            f'    {{"fill_id": {x.fill_id}, "order_id": {x.order_id}, "parent_id": '
            f'{x.parent_id}, "instrument_id": {x.instrument_id}, "venue_id": {x.venue_id}, '
            f'"side": {x.side}, "price_ticks": {x.price_ticks}, "qty": {x.qty}, '
            f'"ts": {x.ts}, "liquidity": "{x.liquidity.name}", "fee": {_g17(x.fee)}, '
            f'"impact_cost": {_g17(x.impact_cost)}}}{"," if i + 1 < len(res.fills) else ""}\n'
        )
    out.append('  ],\n  "parents": {\n')
    for n, (pid, r) in enumerate(res.parents.items()):
        out.append(
            f'    "{pid}": {{"filled_qty": {r.filled_qty}, "unfilled_qty": '
            f'{r.unfilled_qty}, "children": {r.children}, "notional": {_g17(r.notional)}, '
            f'"avg_price": {_g17(r.avg_price)}, "fees": {_g17(r.fees)}, '
            f'"rebates": {_g17(r.rebates)}, "impact": {_g17(r.impact)}, "total_cost": '
            f"{_g17(r.total_cost)}}}{',' if n + 1 < len(res.parents) else ''}\n"
        )
    out.append('  },\n  "passive": {\n')
    for n, (pid, s) in enumerate(res.passive.items()):
        out.append(
            f'    "{pid}": {{"posts": {s.posts}, "reprices": {s.reprices}, '
            f'"rest_extensions": {s.rest_extensions}, "crosses_timeout": '
            f'{s.crosses_timeout}, "crosses_behind": {s.crosses_behind}, '
            f'"crosses_immediate": {s.crosses_immediate}}}'
            f"{',' if n + 1 < len(res.passive) else ''}\n"
        )
    out.append("  }\n}\n")
    return "".join(out)


def run_scenario(golden_dir: Path) -> tuple[ExecReplayResult, int]:
    """Replay the pinned scenario; returns ``(result, t0)``."""
    events = read_jsonl(golden_dir / "events_eq_mbo.jsonl")
    t0 = events[0].exchange_ts
    replay = ExecutionReplay(golden_config(golden_dir.parents[1] / "configs"), golden_parents(t0))
    return replay.run(events), t0


def main() -> int:
    if GOLDEN.exists() and "--force" not in sys.argv:
        print(
            f"{GOLDEN.name} already exists — pinned; pass --force after a "
            "schemas/MIGRATIONS.md entry"
        )
        return 1
    res, t0 = run_scenario(GOLDEN.parent)
    GOLDEN.write_bytes(render(res, t0).encode("utf-8"))
    print(f"wrote {GOLDEN} ({len(res.fills)} fills)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
