#!/usr/bin/env python3
"""Generate the committed risk differential-fuzz corpus under
``tests/golden/risk_fuzz/`` (backlog epic E31; format and generator:
``python/tools/risk_fuzz.py``).

The corpus is a fixed list of ``(profile, seed)`` scripts. Each script is
generated by the state-aware generator, its expectations are recorded by the
Python engine (the oracle), and three files are written per script:
``<name>.json`` (the step script), ``<name>.audit.jsonl`` (the audit log,
byte-exact) and ``<name>.snapshot.json`` (the final state); ``COVERAGE.txt``
lists every reason-string branch of the engine with the first script that
reaches it. Rust
(``rust/risk/tests/golden_risk_fuzz.rs``), Java (``RiskFuzzGoldenTest``) and
Python (``python/tests/test_risk_fuzz_golden.py``) replay every script and must
reproduce all of it byte for byte.

Usage (from the repo root)::

    python python/tools/make_risk_fuzz_corpus.py --check    # fail if it is stale
    python python/tools/make_risk_fuzz_corpus.py --force    # rewrite the corpus
    python python/tools/make_risk_fuzz_corpus.py --out DIR --seed 7 --count 200

``--check`` regenerates everything in memory and compares it with the committed
bytes; CI runs it so a change to an engine, the generator or
``configs/risk/risk.json`` cannot leave a stale corpus behind. Like every
golden tool, a run that would CHANGE existing files refuses without ``--force``
(conventions section 5: a golden moves only deliberately, with a
``schemas/MIGRATIONS.md`` entry). ``--seed`` / ``--count`` write a fresh corpus
(profiles in rotation, seeds from one SplitMix64 stream) to ``--out`` instead —
the nightly job's input.

Files are written with LF line endings and no byte-order mark; generation is
integer / IEEE-754 arithmetic only, so the bytes are the same on every
platform.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

import risk_fuzz as rf  # noqa: E402

CORPUS_DIR = rf.ROOT / "tests" / "golden" / "risk_fuzz"
#: The coverage report written next to the scripts (branch -> first script).
COVERAGE_FILE = "COVERAGE.txt"

#: The committed corpus: ``SEEDS_PER_PROFILE`` scripts of every profile, then
#: one short ``config`` script per configuration mutation.
SEEDS_PER_PROFILE = 3
CORPUS_MASTER_SEED = 31


def corpus_plan() -> list[tuple[str, str, int]]:
    """``(name, profile, seed)`` of every committed script."""
    plan = []
    for k, (profile, seed) in enumerate(
        rf.seeds_from(CORPUS_MASTER_SEED, SEEDS_PER_PROFILE * len(rf.PROFILES))
    ):
        plan.append((f"{k:03d}_{profile}", profile, seed))
    for m in range(len(rf.CONFIG_MUTATIONS)):
        plan.append((f"cfg{m:02d}_config", "config", m))
    return plan


def fresh_plan(master: int, count: int) -> list[tuple[str, str, int]]:
    return [
        (f"s{master}_{k:04d}_{profile}", profile, seed)
        for k, (profile, seed) in enumerate(rf.seeds_from(master, count))
    ]


def build(plan: list[tuple[str, str, int]]) -> tuple[dict[str, bytes], list[Any]]:
    """Generate, self-check and serialise every script of ``plan``."""
    base = rf.load_base_config()
    files: dict[str, bytes] = {}
    corpus = []
    for name, profile, seed in plan:
        script = rf.build_script(profile, seed, base, name)
        audit, snapshot = rf.expected_outputs(script, base)
        # The oracle must satisfy its own replay contract (decisions, bytes,
        # and the restore check at every cut point) before anything is pinned.
        rf.verify_script(script, base, audit, snapshot)
        files.update(rf.script_files(script, base))
        corpus.append((script, audit, snapshot))
    files[COVERAGE_FILE] = rf.coverage_report(corpus).encode("utf-8")
    return files, corpus


def print_coverage(corpus: list[Any]) -> None:
    cov = rf.coverage(corpus)
    print(f"{cov['scripts']} scripts, {cov['steps']} steps, {cov['audit_lines']} audit lines")
    print("step types: " + ", ".join(f"{k} {v}" for k, v in cov["step_types"].items()))
    print("rule ids:   " + ", ".join(f"{k} {v}" for k, v in cov["rules"].items()))
    print(f"reason branches reached: {len(cov['branches_reached'])}/{len(rf.BRANCHES)}")
    for b in cov["branches_missed"]:
        why = rf.UNREACHABLE.get(b)
        print(f"  not reached: {rf.branch_label(b)}" + (f"  [unreachable: {why}]" if why else ""))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed corpus is stale")
    ap.add_argument("--force", action="store_true", help="overwrite files that would change")
    ap.add_argument("--out", type=Path, default=CORPUS_DIR, help="output directory")
    ap.add_argument("--seed", type=int, help="master seed of a fresh (non-committed) corpus")
    ap.add_argument("--count", type=int, default=120, help="scripts of a fresh corpus")
    args = ap.parse_args()

    plan = corpus_plan() if args.seed is None else fresh_plan(args.seed, args.count)
    files, corpus = build(plan)
    on_disk = (
        {p.name: p.read_bytes() for p in sorted(args.out.iterdir()) if p.is_file()}
        if args.out.is_dir()
        else {}
    )
    stale = sorted(n for n in files if on_disk.get(n) != files[n])
    extra = sorted(n for n in on_disk if n not in files)
    if args.check:
        if stale or extra:
            for n in stale:
                print(f"STALE   {n}")
            for n in extra:
                print(f"UNKNOWN {n}")
            print("the committed risk fuzz corpus is stale: rerun make_risk_fuzz_corpus.py")
            return 1
        print(f"risk fuzz corpus is current ({len(files)} files)")
        return 0
    changed = sorted(n for n in stale if n in on_disk) + extra
    if changed and not args.force:
        print(
            f"refusing to change {len(changed)} existing files under {args.out} "
            f"(first: {changed[0]}); pass --force"
        )
        return 2
    for n in extra:
        (args.out / n).unlink()
    rf.write_files(args.out, files)
    print_coverage(corpus)
    print(f"{len(files)} files, {sum(len(b) for b in files.values())} bytes -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
