package com.iap;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.junit.Test;

import com.iap.tca.MarketTimeline;
import com.iap.tca.Markout;

/**
 * Markout golden (tests/golden/expected_markout.json, generated by
 * python/tools/make_golden_markout.py): per-fill measures, the markout
 * report and the passive-order statistics must match the Python reference
 * to the file's tolerance, nulls exactly — plus the sign, decomposition and
 * undefined-markout edge cases on hand-built timelines.
 */
public class MarkoutGoldenTest {
    private static final long T0 = 1_000_000_000_000L;
    private static final long SEC = 1_000_000_000L;
    private static final String[] MEASURES = {
        "markout", "effective_half_spread", "realised_half_spread", "price_impact"};

    private static Map<String, Object> golden() {
        return Golden.json("expected_markout.json");
    }

    private static MarketTimeline timeline(Map<String, Object> g) {
        MarketTimeline tl = new MarketTimeline();
        for (Object row : Json.array(g.get("states"))) {
            List<Object> s = Json.array(row);
            tl.appendStatePinned(Json.asLong(s.get(0)), Json.asDouble(s.get(1)),
                    Json.asDouble(s.get(2)), Json.asLong(s.get(3)),
                    Json.asLong(s.get(4)));
        }
        for (Object gate : Json.array(g.get("gates"))) {
            tl.addHalt(Json.asLong(gate));
        }
        return tl;
    }

    private static List<Markout.Fill> fills(Map<String, Object> g) {
        List<Markout.Fill> out = new ArrayList<>();
        for (Object row : Json.array(g.get("fills"))) {
            List<Object> f = Json.array(row);
            out.add(new Markout.Fill(Json.asLong(f.get(0)), Json.asDouble(f.get(1)),
                    Json.asLong(f.get(2)), (int) Json.asLong(f.get(3)),
                    (String) f.get(4), (int) Json.asLong(f.get(5)),
                    (String) f.get(6), Json.asDouble(f.get(7))));
        }
        return out;
    }

    private static List<Markout.PassiveOrder> orders(Map<String, Object> g) {
        List<Markout.PassiveOrder> out = new ArrayList<>();
        for (Object row : Json.array(g.get("passive_orders"))) {
            List<Object> o = Json.array(row);
            out.add(new Markout.PassiveOrder(Json.asLong(o.get(0)),
                    Json.asLong(o.get(1)), Json.asLong(o.get(2)),
                    (Long) o.get(3), (Long) o.get(4), Json.asLong(o.get(5))));
        }
        return out;
    }

    /** Recursive comparison: same keys, nulls exact, integers exact, doubles at tol. */
    private static void assertTree(String path, Object want, Object got, double tol) {
        if (want == null) {
            assertNull(path, got);
        } else if (want instanceof Map<?, ?> wm) {
            assertTrue(path + " is a map", got instanceof Map<?, ?>);
            Map<?, ?> gm = (Map<?, ?>) got;
            assertEquals(path + " keys", wm.keySet(), gm.keySet());
            for (Map.Entry<?, ?> e : wm.entrySet()) {
                assertTree(path + "." + e.getKey(), e.getValue(), gm.get(e.getKey()), tol);
            }
        } else if (want instanceof List<?> wl) {
            assertTrue(path + " is a list", got instanceof List<?>);
            List<?> gl = (List<?>) got;
            assertEquals(path + " size", wl.size(), gl.size());
            for (int i = 0; i < wl.size(); i++) {
                assertTree(path + "[" + i + "]", wl.get(i), gl.get(i), tol);
            }
        } else if (want instanceof Long wn && got instanceof Long gn) {
            assertEquals(path, wn.longValue(), gn.longValue());
        } else if (want instanceof Number wn) {
            assertNotNull(path, got);
            assertTrue(path + " is a number", got instanceof Number);
            assertEquals(path, wn.doubleValue(), ((Number) got).doubleValue(), tol);
        } else {
            assertEquals(path, want, got);
        }
    }

    @Test
    public void perFillMeasuresMatchWithExactNulls() {
        Map<String, Object> g = golden();
        assertEquals(1, Json.asLong(g.get("x-version")));
        double tol = Json.asDouble(g.get("tolerance"));
        MarketTimeline tl = timeline(g);
        List<Markout.Fill> fills = fills(g);
        List<Object> want = Json.array(Json.object(g.get("expected")).get("per_fill"));
        assertEquals(40, fills.size());
        assertEquals(want.size(), fills.size());
        int nulls = 0;
        for (int i = 0; i < fills.size(); i++) {
            Map<String, Object> row = Json.object(want.get(i));
            for (Map.Entry<String, Long> h : Markout.DEFAULT_HORIZONS_NS.entrySet()) {
                String what = "fill " + i + " " + h.getKey();
                double[] got = Markout.fillMeasures(fills.get(i), tl, h.getValue());
                Object w = row.get(h.getKey());
                assertTrue(what, row.containsKey(h.getKey()));
                if (w == null) {
                    assertNull(what, got);
                    nulls++;
                    continue;
                }
                assertNotNull(what, got);
                Map<String, Object> wm = Json.object(w);
                for (int m = 0; m < MEASURES.length; m++) {
                    assertEquals(what + " " + MEASURES[m],
                            Json.asDouble(wm.get(MEASURES[m])), got[m], tol);
                }
                // effective = realised + impact; markout = -realised
                assertEquals(what, got[1], got[2] + got[3], 1e-12);
                assertEquals(what, -got[2], got[0], 0.0);
            }
        }
        assertTrue(nulls > 40); // every fill's 5 min window, plus the edge cases
    }

    @Test
    public void reportAndPassiveStatsMatch() {
        Map<String, Object> g = golden();
        double tol = Json.asDouble(g.get("tolerance"));
        Map<String, Object> expected = Json.object(g.get("expected"));
        Map<String, Object> report = Markout.report(fills(g), timeline(g),
                Markout.DEFAULT_HORIZONS_NS, (int) Json.asLong(g.get("min_fills")),
                Json.asLong(g.get("bucket_ns")), Json.asLong(g.get("t0")));
        assertTree("report", expected.get("report"), report, tol);
        Map<String, Object> passive = Markout.passiveOrderStats(orders(g),
                (int) Json.asLong(g.get("min_fills")), new long[] {0, 500, 2000});
        assertTree("passive", expected.get("passive"), passive, tol);
    }

    private static MarketTimeline ramp(int n, double step) {
        MarketTimeline tl = new MarketTimeline();
        for (int k = 0; k < n; k++) {
            double m = 100.0 + k * step;
            tl.append(T0 + k * SEC, m - 0.01, m + 0.01, 100, 100);
        }
        return tl;
    }

    @Test
    public void signsAndDecompositionOnARisingMid() {
        MarketTimeline tl = ramp(400, 0.01);
        Markout.Fill buy = new Markout.Fill(T0, 100.01, 10, 0, "TAKER", 1, "IS", 1.0);
        double[] x = Markout.fillMeasures(buy, tl, 5 * SEC);
        assertEquals(0.04, x[0], 1e-9);  // bought, the mid went up: good
        assertEquals(0.01, x[1], 1e-9);  // paid the half-spread
        assertEquals(-0.04, x[2], 1e-9);
        assertEquals(0.05, x[3], 1e-9);
        Markout.Fill sell = new Markout.Fill(T0, 99.99, 10, 1, "TAKER", 1, "IS", 1.0);
        double[] y = Markout.fillMeasures(sell, tl, 5 * SEC);
        assertEquals(-0.06, y[0], 1e-9); // sold, the mid went up: bad
        assertEquals(0.01, y[1], 1e-9);
        assertEquals(-0.05, y[3], 1e-9);
        // at or before the horizon: no interpolation, no look-ahead
        assertEquals(100.05, Markout.markoutMid(tl, T0, 5 * SEC + SEC / 2), 1e-9);
    }

    @Test
    public void makerFillUsesThePreEventStateAndShowsAdverseSelection() {
        MarketTimeline tl = new MarketTimeline();
        tl.append(T0, 99.98, 100.02, 100, 100);
        tl.append(T0 + 1000, 99.90, 100.02, 100, 100);
        for (int k = 1; k < 20; k++) {
            tl.append(T0 + k * SEC, 99.90, 99.94, 100, 100);
        }
        Markout.Fill f = new Markout.Fill(T0 + 1000, 99.98, 100, 0, "MAKER", 1, "TWAP", 1.0);
        assertEquals(100.0, Markout.referenceMid(tl, f.ts(), "MAKER"), 1e-9);
        assertEquals(99.96, Markout.referenceMid(tl, f.ts(), "TAKER"), 1e-9);
        double[] x = Markout.fillMeasures(f, tl, 5 * SEC);
        assertEquals(-0.02, x[1], 1e-9); // earned 2 cents
        assertEquals(-0.08, x[3], 1e-9); // the mid moved against us
        assertEquals(0.06, x[2], 1e-9);  // net: lost 6 cents
        Map<String, Object> rep = Markout.report(List.of(f, f, f), tl,
                Markout.DEFAULT_HORIZONS_NS, 2, 300 * SEC, T0);
        Map<String, Object> adv = Json.object(
                Json.object(rep.get("adverse_selection")).get("5s"));
        assertEquals(3L, adv.get("n"));
        assertEquals(1e4 * 0.08 / 99.98, (Double) adv.get("bps"), 1e-9);
        assertEquals(3 * 0.08 * 100, (Double) adv.get("ccy"), 1e-9);
    }

    @Test
    public void undefinedMarkoutsAreNullNeverZero() {
        MarketTimeline flat = new MarketTimeline();
        for (int k = 0; k < 61; k++) {
            flat.append(T0 + k * SEC, 99.99, 100.01, 100, 100);
        }
        long end = flat.lastTs();
        assertNotNull(Markout.markoutMid(flat, end, 0));
        assertNull(Markout.markoutMid(flat, end, 1));               // past the data
        assertNull(Markout.markoutMid(flat, end - 5 * SEC, 30 * SEC));
        assertNull(Markout.markoutMid(flat, T0 - 10 * SEC, SEC));   // no quote yet
        assertNull(Markout.fillMeasures(new Markout.Fill(T0 - SEC, 100.0, 10, 0,
                "TAKER", 1, "IS", 1.0), flat, 5 * SEC));            // no reference mid

        MarketTimeline gap = new MarketTimeline();
        for (int k = 0; k < 10; k++) {
            gap.append(T0 + k * SEC, 99.99, 100.01, 100, 100);
        }
        for (int k = 30; k < 60; k++) {
            gap.append(T0 + k * SEC, 99.99, 100.01, 100, 100);
        }
        gap.addHalt(T0 + 10 * SEC);
        assertNotNull(Markout.markoutMid(gap, T0 + 2 * SEC, 5 * SEC));
        assertNull(Markout.markoutMid(gap, T0 + 2 * SEC, 8 * SEC));   // gate at the horizon
        assertNull(Markout.markoutMid(gap, T0 + 2 * SEC, 40 * SEC));  // gate inside
        assertNull(Markout.markoutMid(gap, T0 + 15 * SEC, 5 * SEC));  // quote predates gate
        assertNotNull(Markout.markoutMid(gap, T0 + 31 * SEC, 5 * SEC));
        assertNull(Markout.referenceMid(gap, T0 + 15 * SEC, "TAKER"));

        // a cell with too few defined fills: n reported, statistics null
        Markout.Fill f = new Markout.Fill(end - 5 * SEC, 100.01, 10, 0, "TAKER", 1, "IS", 1.0);
        Map<String, Object> rep = Markout.report(List.of(f, f, f, f, f, f), flat,
                Markout.DEFAULT_HORIZONS_NS, 5, 300 * SEC, T0);
        Map<String, Object> hz = Json.object(Json.object(rep.get("all")).get("horizons"));
        assertEquals(6L, Json.object(hz.get("5s")).get("n"));
        assertNotNull(Json.object(hz.get("5s")).get("markout_bps"));
        assertEquals(0L, Json.object(hz.get("30s")).get("n"));
        assertNull(Json.object(hz.get("30s")).get("markout_bps"));
        assertNull(Json.object(hz.get("30s")).get("markout_ccy"));
    }

    @Test
    public void passiveOrderStatsAndValidation() {
        List<Markout.PassiveOrder> orders = List.of(
                new Markout.PassiveOrder(100, 100, T0, T0 + 2 * SEC, T0 + 4 * SEC, 0),
                new Markout.PassiveOrder(100, 100, T0, T0 + 4 * SEC, T0 + 4 * SEC, 0),
                new Markout.PassiveOrder(100, 50, T0, T0 + 6 * SEC, T0 + 6 * SEC, 0),
                new Markout.PassiveOrder(200, 0, T0, null, null, 5000),
                new Markout.PassiveOrder(200, 0, T0, null, null, 5000),
                new Markout.PassiveOrder(200, 200, T0, T0 + 30 * SEC, T0 + 30 * SEC, 5000),
                new Markout.PassiveOrder(100, 0, T0, null, null, 400));
        long[] edges = {0, 500, 2000};
        Map<String, Object> rep = Markout.passiveOrderStats(orders, 3, edges);
        Map<String, Object> all = Json.object(rep.get("all"));
        assertEquals(7L, all.get("n_orders"));
        assertEquals(0.45, (Double) all.get("fill_rate_qty"), 1e-12);
        assertEquals(4.0 / 7, (Double) all.get("fill_rate_orders"), 1e-12);
        assertEquals(3.0 / 7, (Double) all.get("full_fill_rate"), 1e-12);
        assertEquals(10.5 * SEC,
                (Double) Json.object(all.get("time_to_first_fill_ns")).get("mean"), 1e-3);
        Map<String, Object> byQueue = Json.object(rep.get("by_queue_ahead_at_entry"));
        assertEquals(List.of("0", "1-500", ">2000"), new ArrayList<>(byQueue.keySet()));
        assertEquals(250.0 / 300,
                (Double) Json.object(byQueue.get("0")).get("fill_rate_qty"), 1e-12);
        assertNull(Json.object(byQueue.get("1-500")).get("fill_rate_qty"));
        assertEquals("501-2000", Markout.queueBucket(501, edges));
        assertEquals(">2000", Markout.queueBucket(2001, edges));
        int rejected = 0;
        try {
            new Markout.PassiveOrder(100, 101, T0, T0, T0, 0);
            fail("overfilled order must be rejected");
        } catch (IllegalArgumentException expected) {
            rejected++;
        }
        try {
            new Markout.Fill(T0, 1.0, 1, 0, "X", 1, "IS", 1.0);
            fail("unknown liquidity must be rejected");
        } catch (IllegalArgumentException expected) {
            rejected++;
        }
        try {
            Markout.passiveOrderStats(orders, 3, new long[] {1, 5});
            fail("edges must start at 0");
        } catch (IllegalArgumentException expected) {
            rejected++;
        }
        assertEquals(3, rejected);
    }
}
