package com.iap;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.junit.Test;

import com.iap.core.MarketEvent;
import com.iap.core.SplitMix64;
import com.iap.execution.AlgoType;
import com.iap.execution.ExecConfig;
import com.iap.execution.ExecutionReplay;
import com.iap.execution.Fill;
import com.iap.execution.InstrumentSpec;
import com.iap.execution.LatencyConfig;
import com.iap.execution.Liquidity;
import com.iap.execution.ParentOrder;
import com.iap.execution.VenueSpec;

/**
 * Golden execution-replay fills (tests/golden/expected_replay_fills.json):
 * events_eq_mbo.jsonl (instrument 1, venue XV1, tick 0.01) worked by
 * parent 1 = VWAP BUY 400 over [t0+60s, t0+660s) in 4 passive LIMIT slices
 * joining the best bid (quantities {129, 71, 71, 129}), and parent 2 =
 * IS SELL 600 over [t0+120s, t0+720s) in 3 front-loaded MARKET slices
 * (risk_aversion 1.0; quantities {304, 184, 112}). MUST reproduce the
 * golden fills exactly (ticks/qty/ts; fee/impact at 1e-9).
 */
public class ReplayFillsGoldenTest {
    private static final long SEC = 1_000_000_000L;

    private static ExecConfig goldenConfig() {
        TreeMap<Integer, VenueSpec> venues = VenueSpec.loadVenues(
                Paths.get("..", "configs", "venues.json"));
        TreeMap<Long, InstrumentSpec> instruments = new TreeMap<>();
        instruments.put(1L, new InstrumentSpec(1, 0.01, 1.0, 38_000_000.0));
        return new ExecConfig(LatencyConfig.DEFAULT, 20260829L, 2.0,
                instruments, venues);
    }

    private static List<ParentOrder> goldenParents(long t0) {
        ParentOrder vwap = new ParentOrder();
        vwap.parentId = 1;
        vwap.instrumentId = 1;
        vwap.venueId = 1;
        vwap.side = 0;
        vwap.qty = 400;
        vwap.algo = AlgoType.VWAP;
        vwap.startTs = t0 + 60 * SEC;
        vwap.endTs = t0 + 660 * SEC;
        vwap.slices = 4;
        ParentOrder is = new ParentOrder();
        is.parentId = 2;
        is.instrumentId = 1;
        is.venueId = 1;
        is.side = 1;
        is.qty = 600;
        is.algo = AlgoType.IS;
        is.startTs = t0 + 120 * SEC;
        is.endTs = t0 + 720 * SEC;
        is.slices = 3;
        is.riskAversion = 1.0;
        return List.of(vwap, is);
    }

    private static ExecutionReplay.Result runGoldenScenario() {
        List<MarketEvent> events = Golden.eq();
        ExecutionReplay replay = new ExecutionReplay(goldenConfig(),
                goldenParents(events.get(0).exchangeTs));
        return replay.run(events);
    }

    @Test
    public void exactFillListMatches() {
        // expected_replay_fills.json is regenerated by the C++ reference
        // from the regenerated event vectors (schemas/MIGRATIONS.md).
        Map<String, Object> golden = Golden.json("expected_replay_fills.json");
        ExecutionReplay.Result res = runGoldenScenario();
        assertEquals(Json.asLong(golden.get("events_processed")),
                res.eventsProcessed);
        List<Object> fills = Json.array(golden.get("fills"));
        assertEquals(fills.size(), res.fills.size());
        for (int i = 0; i < fills.size(); i++) {
            Map<String, Object> want = Json.object(fills.get(i));
            Fill got = res.fills.get(i);
            String what = "fill " + (i + 1);
            assertEquals(what, Json.asLong(want.get("fill_id")), got.fillId());
            assertEquals(what, Json.asLong(want.get("order_id")), got.orderId());
            assertEquals(what, Json.asLong(want.get("parent_id")), got.parentId());
            assertEquals(what, Json.asLong(want.get("instrument_id")),
                    got.instrumentId());
            assertEquals(what, Json.asLong(want.get("venue_id")), got.venueId());
            assertEquals(what, Json.asLong(want.get("side")), got.side());
            assertEquals(what, Json.asLong(want.get("price_ticks")),
                    got.priceTicks()); // exact
            assertEquals(what, Json.asLong(want.get("qty")), got.qty()); // exact
            assertEquals(what, Json.asLong(want.get("ts")), got.ts());   // exact
            assertEquals(what, want.get("liquidity"),
                    got.liquidity() == Liquidity.MAKER ? "MAKER" : "TAKER");
            assertEquals(what, Json.asDouble(want.get("fee")), got.fee(), 1e-9);
            assertEquals(what, Json.asDouble(want.get("impact_cost")),
                    got.impactCost(), 1e-9);
        }
        // Parent reports.
        Map<String, Object> parents = Json.object(golden.get("parents"));
        for (String pid : new String[] {"1", "2"}) {
            Map<String, Object> want = Json.object(parents.get(pid));
            ExecutionReplay.ParentReport got = res.parents.get(Long.parseLong(pid));
            assertEquals(Json.asLong(want.get("filled_qty")), got.filledQty);
            assertEquals(Json.asLong(want.get("unfilled_qty")), got.unfilledQty);
            assertEquals(Json.asLong(want.get("children")), got.children);
            assertEquals(Json.asDouble(want.get("notional")), got.notional, 1e-9);
            assertEquals(Json.asDouble(want.get("avg_price")), got.avgPrice, 1e-9);
            assertEquals(Json.asDouble(want.get("fees")), got.fees, 1e-9);
            assertEquals(Json.asDouble(want.get("rebates")), got.rebates, 1e-9);
            assertEquals(Json.asDouble(want.get("impact")), got.impact, 1e-9);
            assertEquals(Json.asDouble(want.get("total_cost")), got.totalCost, 1e-9);
            // Identity: total_cost = fees - rebates + impact.
            assertEquals(got.fees - got.rebates + got.impact, got.totalCost, 1e-12);
        }
    }

    @Test
    public void handTracedFirstFills() {
        ExecutionReplay.Result res = runGoldenScenario();
        assertTrue(res.fills.size() >= 2);

        // The jitter draws come from SplitMix64(20260829), submission order:
        // order 1 = VWAP slice 0 (starts t0+60s), order 2 = IS slice 0.
        SplitMix64 rng = new SplitMix64(20260829L);
        long j1 = rng.below(50_000 + 1);
        long j2 = rng.below(50_000 + 1);
        assertEquals(21675, j1);
        assertEquals(14614, j2);

        // Fill 1: IS slice 0 — aggressive at the 2451 ask, stamped with its
        // arrival_ts (decision at event index 73, the first event at or
        // after t0+120s).
        Fill f1 = res.fills.get(0);
        assertEquals(2, f1.orderId());
        assertEquals(2, f1.parentId());
        assertEquals(304, f1.qty()); // IS slice quantities {304, 184, 112}
        assertEquals(2451, f1.priceTicks());
        assertEquals(Liquidity.TAKER, f1.liquidity());
        long decision2 = 1787578329585937884L; // event index 73
        assertEquals(decision2 + 350_000 + j2, f1.ts());
        assertEquals(0.003 * 304, f1.fee(), 0.0);
        // Linear impact: 2.0 * (304/38e6*100) bps over notional 304*24.51.
        double impactBps = 2.0 * (304.0 / 38_000_000.0 * 100.0);
        assertEquals(impactBps * 1e-4 * (304.0 * 2451 * 0.01),
                f1.impactCost(), 1e-15);

        // Fill 2: VWAP slice 0 — passive join at the 2449 bid (decision at
        // event index 47, the first event at or after t0+60s), filled by
        // the ask ADD at 2448 trading through it (event index 97).
        Fill f2 = res.fills.get(1);
        assertEquals(1, f2.orderId());
        assertEquals(1, f2.parentId());
        assertEquals(129, f2.qty()); // VWAP slice quantities {129,71,71,129}
        assertEquals(2449, f2.priceTicks());
        assertEquals(Liquidity.MAKER, f2.liquidity());
        assertEquals(1787578386181246977L, f2.ts());
        assertEquals(-0.002 * 129, f2.fee(), 0.0);
        long decision1 = 1787578263509538609L; // event index 47
        assertEquals(1787578263509910284L, decision1 + 350_000 + j1);
        assertTrue(f2.ts() > decision1 + 350_000 + j1); // fill after arrival
    }

    @Test
    public void deterministicRerun() {
        ExecutionReplay.Result a = runGoldenScenario();
        ExecutionReplay.Result b = runGoldenScenario();
        assertEquals(a.fills.size(), b.fills.size());
        for (int i = 0; i < a.fills.size(); i++) {
            assertEquals(a.fills.get(i), b.fills.get(i)); // record equality
        }
    }

    @Test
    public void bothParentsCompleteWithMixedLiquidity() {
        ExecutionReplay.Result res = runGoldenScenario();
        // Scenario shape (golden v2): parent 1 fills passively (maker) except
        // its slice-2 child (71 @ 2448), which EXPIRES at end_ts (rule 7 —
        // in v1 it filled 290 s after the window); parent 2 fills entirely
        // aggressively (taker) in full.
        long makerQty = 0;
        long takerQty = 0;
        for (Fill f : res.fills) {
            if (f.liquidity() == Liquidity.MAKER) {
                assertEquals(1, f.parentId());
                assertEquals(0.0, f.impactCost(), 0.0); // passive: no impact
                makerQty += f.qty();
            } else {
                assertEquals(2, f.parentId());
                assertTrue(f.impactCost() > 0.0);
                takerQty += f.qty();
            }
        }
        assertEquals(329, makerQty);
        assertEquals(600, takerQty);
        assertEquals(71, res.parents.get(1L).unfilledQty);
        // every attributed fill lies inside its parent's window (pinned)
        long t0 = Golden.eq().get(0).exchangeTs;
        for (Fill f : res.fills) {
            long end = t0 + (f.parentId() == 1 ? 660 : 720) * 1_000_000_000L;
            assertTrue(f.ts() <= end);
        }
        assertEquals(4, res.parents.get(1L).children);
        assertTrue(replayExpiredCount(res) >= 1);
    }

    private static long replayExpiredCount(ExecutionReplay.Result res) {
        // the expired child is reported unfilled: 400 - 329
        return res.parents.get(1L).unfilledQty > 0 ? 1 : 0;
    }

    @Test
    public void oneShotRunEnforced() {
        List<MarketEvent> events = Golden.eq();
        ExecutionReplay replay = new ExecutionReplay(goldenConfig(),
                goldenParents(events.get(0).exchangeTs));
        replay.run(events);
        try {
            replay.run(events);
            throw new AssertionError("second run must throw");
        } catch (IllegalStateException expected) {
            // pinned behavior
        }
    }
}
