package com.iap;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.junit.Test;

import com.iap.core.MarketEvent;
import com.iap.execution.AlgoType;
import com.iap.execution.ExecConfig;
import com.iap.execution.ExecPolicy;
import com.iap.execution.ExecutionReplay;
import com.iap.execution.Fill;
import com.iap.execution.InstrumentSpec;
import com.iap.execution.LatencyConfig;
import com.iap.execution.Liquidity;
import com.iap.execution.ParentOrder;
import com.iap.execution.PassiveStats;
import com.iap.execution.VenueSpec;

/**
 * Execution-policy golden (tests/golden/expected_replay_fills_passive.json,
 * generated by python/tools/make_golden_replay_passive.py in the bytes of
 * the C++ generator): events_eq_mbo.jsonl worked by parent 1 = VWAP BUY 400
 * PASSIVE (urgency 0.5), parent 2 = IS SELL 600 PASSIVE (urgency 0.2,
 * risk_aversion 1.0), parent 3 = POV BUY 300 PASSIVE (urgency 0.0,
 * participation 0.1, SOR-routed) and parent 4 = TWAP SELL 200 AGGRESSIVE.
 * MUST reproduce every fill (ticks/qty/ts exact; fee/impact at 1e-9) and
 * every state-machine transition counter.
 */
public class ReplayFillsPassiveGoldenTest {
    private static final long SEC = 1_000_000_000L;

    private static ExecConfig goldenConfig() {
        TreeMap<Integer, VenueSpec> venues = VenueSpec.loadVenues(
                Paths.get("..", "configs", "venues", "venues.json"));
        TreeMap<Long, InstrumentSpec> instruments = new TreeMap<>();
        instruments.put(1L, new InstrumentSpec(1, 0.01, 1.0, 38_000_000.0));
        return new ExecConfig(LatencyConfig.DEFAULT, 20260829L, 2.0,
                instruments, venues);
    }

    private static ParentOrder parent(long id, int venue, int side, long qty,
            AlgoType algo, long start, long end, ExecPolicy policy, double urgency) {
        ParentOrder p = new ParentOrder();
        p.parentId = id;
        p.instrumentId = 1;
        p.venueId = venue;
        p.side = side;
        p.qty = qty;
        p.algo = algo;
        p.startTs = start;
        p.endTs = end;
        p.policy = policy;
        p.urgency = urgency;
        return p;
    }

    private static List<ParentOrder> goldenParents(long t0) {
        ParentOrder vwap = parent(1, 1, 0, 400, AlgoType.VWAP, t0 + 60 * SEC,
                t0 + 660 * SEC, ExecPolicy.PASSIVE, 0.5);
        vwap.slices = 4;
        ParentOrder is = parent(2, 1, 1, 600, AlgoType.IS, t0 + 120 * SEC,
                t0 + 720 * SEC, ExecPolicy.PASSIVE, 0.2);
        is.slices = 3;
        is.riskAversion = 1.0;
        ParentOrder pov = parent(3, 0, 0, 300, AlgoType.POV, t0 + 90 * SEC,
                t0 + 690 * SEC, ExecPolicy.PASSIVE, 0.0);
        pov.participation = 0.1;
        ParentOrder twap = parent(4, 1, 1, 200, AlgoType.TWAP, t0 + 150 * SEC,
                t0 + 450 * SEC, ExecPolicy.AGGRESSIVE, 0.5);
        twap.slices = 4;
        return List.of(vwap, is, pov, twap);
    }

    private static ExecutionReplay.Result runGoldenScenario() {
        List<MarketEvent> events = Golden.eq();
        ExecutionReplay replay = new ExecutionReplay(goldenConfig(),
                goldenParents(events.get(0).exchangeTs));
        return replay.run(events);
    }

    @Test
    public void exactFillListAndTransitionCountersMatch() {
        Map<String, Object> golden = Golden.json("expected_replay_fills_passive.json");
        assertEquals(1, Json.asLong(golden.get("x-version")));
        ExecutionReplay.Result res = runGoldenScenario();
        assertEquals(Json.asLong(golden.get("events_processed")),
                res.eventsProcessed);
        List<Object> fills = Json.array(golden.get("fills"));
        assertEquals(fills.size(), res.fills.size());
        for (int i = 0; i < fills.size(); i++) {
            Map<String, Object> want = Json.object(fills.get(i));
            Fill got = res.fills.get(i);
            String what = "fill " + (i + 1);
            assertEquals(what, Json.asLong(want.get("fill_id")), got.fillId());
            assertEquals(what, Json.asLong(want.get("order_id")), got.orderId());
            assertEquals(what, Json.asLong(want.get("parent_id")), got.parentId());
            assertEquals(what, Json.asLong(want.get("instrument_id")),
                    got.instrumentId());
            assertEquals(what, Json.asLong(want.get("venue_id")), got.venueId());
            assertEquals(what, Json.asLong(want.get("side")), got.side());
            assertEquals(what, Json.asLong(want.get("price_ticks")),
                    got.priceTicks()); // exact
            assertEquals(what, Json.asLong(want.get("qty")), got.qty()); // exact
            assertEquals(what, Json.asLong(want.get("ts")), got.ts());   // exact
            assertEquals(what, want.get("liquidity"),
                    got.liquidity() == Liquidity.MAKER ? "MAKER" : "TAKER");
            assertEquals(what, Json.asDouble(want.get("fee")), got.fee(), 1e-9);
            assertEquals(what, Json.asDouble(want.get("impact_cost")),
                    got.impactCost(), 1e-9);
        }
        Map<String, Object> parents = Json.object(golden.get("parents"));
        assertEquals(4, parents.size());
        for (String pid : new String[] {"1", "2", "3", "4"}) {
            Map<String, Object> want = Json.object(parents.get(pid));
            ExecutionReplay.ParentReport got = res.parents.get(Long.parseLong(pid));
            assertEquals(Json.asLong(want.get("filled_qty")), got.filledQty);
            assertEquals(Json.asLong(want.get("unfilled_qty")), got.unfilledQty);
            assertEquals(Json.asLong(want.get("children")), got.children);
            assertEquals(Json.asDouble(want.get("notional")), got.notional, 1e-9);
            assertEquals(Json.asDouble(want.get("avg_price")), got.avgPrice, 1e-9);
            assertEquals(Json.asDouble(want.get("fees")), got.fees, 1e-9);
            assertEquals(Json.asDouble(want.get("rebates")), got.rebates, 1e-9);
            assertEquals(Json.asDouble(want.get("impact")), got.impact, 1e-9);
            assertEquals(Json.asDouble(want.get("total_cost")), got.totalCost, 1e-9);
            assertEquals(got.fees - got.rebates + got.impact, got.totalCost, 1e-12);
        }
        Map<String, Object> passive = Json.object(golden.get("passive"));
        assertEquals(3, passive.size());
        assertEquals(3, res.passive.size());
        for (String pid : new String[] {"1", "2", "3"}) {
            Map<String, Object> want = Json.object(passive.get(pid));
            PassiveStats got = res.passive.get(Long.parseLong(pid));
            assertEquals(pid, Json.asLong(want.get("posts")), got.posts);
            assertEquals(pid, Json.asLong(want.get("reprices")), got.reprices);
            assertEquals(pid, Json.asLong(want.get("rest_extensions")),
                    got.restExtensions);
            assertEquals(pid, Json.asLong(want.get("crosses_timeout")),
                    got.crossesTimeout);
            assertEquals(pid, Json.asLong(want.get("crosses_behind")),
                    got.crossesBehind);
            assertEquals(pid, Json.asLong(want.get("crosses_immediate")),
                    got.crossesImmediate);
        }
    }

    @Test
    public void feeSignsFollowTheLiquidityFlagAndNoParentOverfills() {
        ExecutionReplay.Result res = runGoldenScenario();
        long makerQty = 0;
        long takerQty = 0;
        for (Fill f : res.fills) {
            if (f.liquidity() == Liquidity.MAKER) {
                assertTrue(f.fee() < 0.0);                 // rebate received
                assertEquals(0.0, f.impactCost(), 0.0);
                assertTrue(f.parentId() != 4);             // AGGRESSIVE never rests
                makerQty += f.qty();
            } else {
                assertTrue(f.fee() > 0.0);                 // taker fee paid
                assertTrue(f.impactCost() > 0.0);
                takerQty += f.qty();
            }
        }
        assertTrue(makerQty > 0 && takerQty > 0);
        long[] qty = {0, 400, 600, 300, 200};
        for (long pid = 1; pid <= 4; pid++) {
            ExecutionReplay.ParentReport rep = res.parents.get(pid);
            assertEquals(qty[(int) pid], rep.filledQty + rep.unfilledQty);
            assertTrue(rep.filledQty <= qty[(int) pid]);
        }
    }

    @Test
    public void deterministicRerun() {
        ExecutionReplay.Result a = runGoldenScenario();
        ExecutionReplay.Result b = runGoldenScenario();
        assertEquals(a.fills.size(), b.fills.size());
        for (int i = 0; i < a.fills.size(); i++) {
            assertEquals(a.fills.get(i), b.fills.get(i)); // record equality
        }
    }
}
