package com.iap;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;
import java.util.stream.Stream;

import org.junit.Test;

import com.iap.risk.InstrumentRef;
import com.iap.risk.OrderRequest;
import com.iap.risk.RiskDecision;
import com.iap.risk.RiskEngine;
import com.iap.risk.RiskEvent;
import com.iap.risk.RiskFill;
import com.iap.risk.RiskLimits;
import com.iap.risk.Scope;

/**
 * Replay of the risk differential-fuzz corpus ({@code tests/golden/risk_fuzz/},
 * generated by {@code python/tools/make_risk_fuzz_corpus.py}; format and
 * generator: {@code python/tools/risk_fuzz.py}) — the Java side of the
 * three-language parity proof (Rust {@code rust/risk/tests/golden_risk_fuzz.rs},
 * Python {@code python/tests/test_risk_fuzz_golden.py}).
 *
 * <p>Every script is replayed through the engine: each order step's decision,
 * rule, severity, scope, scope id and reason must match, the audit JSONL must
 * be byte-identical, the final snapshot must be the same document, and at
 * every cut point a snapshot -&gt; JSON text -&gt; restore -&gt; continue run
 * must produce exactly the unbroken run's remaining audit lines and final
 * state.
 *
 * <p>Two environment variables turn the same test into the nightly job's
 * engine driver ({@code python/tools/risk_fuzz_nightly.py}):
 * {@code IAP_RISK_FUZZ_DIR} replays that directory instead of the committed
 * corpus, and {@code IAP_RISK_FUZZ_OUT} makes the test REPORT instead of
 * fail — it writes {@code java.tsv} ({@code name<TAB>OK} or
 * {@code name<TAB>DIVERGED<TAB>why} per script),
 * {@code <name>.java.audit.jsonl} and {@code <name>.java.snapshot.json} (the
 * audit and final state actually produced) there.
 *
 * <p>NaN and Infinity cannot be carried in JSON, so no script contains them;
 * {@link #nonFiniteInputsAreRejectedLikeTheOtherPorts} pins those inputs.
 */
public class RiskFuzzGoldenTest {
    private static final Path CORPUS = Golden.DIR.resolve("risk_fuzz");

    /** A replay did not reproduce the recorded expectation. */
    private static final class Divergence extends RuntimeException {
        private static final long serialVersionUID = 1L;

        Divergence(String message) {
            super(message);
        }
    }

    private record Case(String name, Map<String, Object> script, String audit,
            String snapshot) {
    }

    private record Run(String audit, int mark, String snapshot) {
    }

    private static Path envDir(String name) {
        String v = System.getenv(name);
        return v == null || v.isEmpty() ? null : Paths.get(v);
    }

    private static String read(Path path) {
        try {
            return new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException("cannot read " + path, e);
        }
    }

    private static void write(Path path, String text) {
        try {
            Files.write(path, text.getBytes(StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new IllegalStateException("cannot write " + path, e);
        }
    }

    /** Every script of a corpus directory, by file name. */
    private static List<Case> loadCorpus(Path dir) {
        List<String> names;
        try (Stream<Path> files = Files.list(dir)) {
            names = files.map(p -> p.getFileName().toString())
                    .filter(n -> n.endsWith(".json") && !n.endsWith(".snapshot.json"))
                    .map(n -> n.substring(0, n.length() - ".json".length()))
                    .sorted()
                    .toList();
        } catch (IOException e) {
            throw new IllegalStateException("cannot list " + dir, e);
        }
        List<Case> out = new ArrayList<>();
        for (String name : names) {
            out.add(new Case(name,
                    Json.object(Json.parse(read(dir.resolve(name + ".json")))),
                    read(dir.resolve(name + ".audit.jsonl")),
                    read(dir.resolve(name + ".snapshot.json"))));
        }
        return out;
    }

    /** The committed config with the script's config_remove / config_set. */
    private static Map<String, Object> effectiveConfig(Map<String, Object> script) {
        Map<String, Object> doc = RiskGoldenTest.config(script);
        if (script.get("config_remove") != null) {
            List<Object> rm = Json.array(script.get("config_remove"));
            if (rm.size() == 1) {
                doc.remove((String) rm.get(0));
            } else {
                Json.object(doc.get((String) rm.get(0))).remove((String) rm.get(1));
            }
        }
        if (script.get("config_set") != null) {
            for (Object s : Json.array(script.get("config_set"))) {
                List<Object> set = Json.array(s);
                Json.object(doc.get((String) set.get(0)))
                        .put((String) set.get(1), set.get(2));
            }
        }
        return doc;
    }

    private static boolean validConfig(Map<String, Object> doc) {
        try {
            RiskLimits.fromJson(doc);
            return true;
        } catch (RuntimeException e) {
            return false;
        }
    }

    private static RiskFill parseFill(Map<String, Object> v) {
        return new RiskFill(
                Json.asLong(v.get("ts")),
                (String) v.get("strategy_id"),
                Json.asLong(v.get("instrument_id")),
                Json.asLong(v.get("order_id")),
                (int) Json.asLong(v.get("side")),
                Json.asLong(v.get("qty")),
                Json.asLong(v.get("price_ticks")));
    }

    /**
     * One replay of a script; {@code done} holds the audit of engines
     * already replaced by a restore.
     */
    private static final class Runner {
        final Map<String, Object> doc;
        final TreeMap<Long, InstrumentRef> refs;
        RiskEngine eng;
        final StringBuilder done = new StringBuilder();
        int doneLines;

        Runner(Map<String, Object> script) {
            doc = effectiveConfig(script);
            refs = RiskGoldenTest.instruments(script);
            eng = RiskEngine.fromConfig(doc, refs);
            if (Boolean.TRUE.equals(script.get("require_bootstrap"))) {
                eng.requireBootstrap();
            }
        }

        int lineCount() {
            return doneLines + eng.audit().size();
        }

        String audit() {
            return done + eng.auditJsonl();
        }

        /**
         * Final snapshot plus a newline; empty for a fail-closed
         * configuration (it cannot be restored).
         */
        String snapshotText() {
            return validConfig(doc) ? eng.snapshot() + "\n" : "";
        }

        /** Snapshot through the JSON text and continue on the restored engine. */
        void restore(long ts) {
            done.append(eng.auditJsonl());
            doneLines += eng.audit().size();
            eng = RiskEngine.restore(RiskLimits.fromJson(doc), refs,
                    Json.object(Json.parse(eng.snapshot())), ts);
        }

        private boolean callFails(String kind, Map<String, Object> step) {
            Scope scope = Scope.parse((String) step.get("scope"));
            String scopeId = (String) step.get("scope_id");
            long ts = Json.asLong(step.get("ts"));
            try {
                switch (kind) {
                    case "kill", "bad_kill" -> eng.engageKill(scope, scopeId, ts,
                            (String) step.getOrDefault("reason", ""));
                    case "unkill", "bad_unkill" -> eng.clearKill(scope, scopeId, ts,
                            (String) step.getOrDefault("reason", ""));
                    default -> eng.overrideLossLimit(scope, scopeId,
                            Json.asDouble(step.get("new_limit")), ts,
                            (String) step.getOrDefault("approver", ""));
                }
                return false;
            } catch (IllegalArgumentException | IllegalStateException refused) {
                return true;
            }
        }

        /** Apply step {@code i}; with {@code check}, compare with the expectation. */
        void apply(int i, Map<String, Object> step, boolean check) {
            String kind = (String) step.get("type");
            switch (kind) {
                case "order" -> {
                    OrderRequest order = RiskGoldenTest.parseOrder(
                            Json.object(step.get("order")));
                    RiskDecision d = eng.checkOrder(order);
                    if (check) {
                        List<RiskEvent> log = eng.audit();
                        RiskEvent ev = log.get(log.size() - 1);
                        Map<String, Object> got = new LinkedHashMap<>();
                        got.put("decision", (long) d.decision().code());
                        got.put("rule_id", d.ruleId());
                        got.put("severity", (long) d.severity().code());
                        got.put("scope", ev.scope().name());
                        got.put("scope_id", ev.scopeId());
                        got.put("reason", d.reason());
                        if (!got.equals(step.get("expect"))) {
                            throw new Divergence("step " + i + " order "
                                    + Long.toUnsignedString(order.orderId()) + ": got "
                                    + got + ", want " + step.get("expect"));
                        }
                    }
                }
                case "market" -> eng.onMarket(
                        Json.asLong(step.get("instrument_id")),
                        Json.asLong(step.get("bid_ticks")),
                        Json.asLong(step.get("ask_ticks")),
                        Json.asLong(step.get("ts")));
                case "fill" -> eng.onFill(parseFill(step));
                case "cancel" -> eng.onOrderDone(Json.asLong(step.get("order_id")));
                case "gap" -> eng.onSequenceGap(
                        Json.asLong(step.get("instrument_id")),
                        Json.asLong(step.get("ts")));
                case "recover" -> eng.onFeedRecovered(
                        Json.asLong(step.get("instrument_id")),
                        Json.asLong(step.get("ts")));
                case "venue_down" -> eng.onVenueDisconnect(
                        (int) Json.asLong(step.get("venue_id")),
                        Json.asLong(step.get("ts")));
                case "venue_up" -> eng.onVenueReconnect(
                        (int) Json.asLong(step.get("venue_id")),
                        Json.asLong(step.get("ts")));
                case "kill", "bad_kill", "unkill", "bad_unkill", "override_loss",
                        "bad_override" -> {
                    boolean failed = callFails(kind, step);
                    if (check && failed != kind.startsWith("bad_")) {
                        throw new Divergence("step " + i + " " + kind + ": the call "
                                + (failed ? "failed" : "succeeded"));
                    }
                }
                case "roll_session" -> eng.rollSession(Json.asLong(step.get("ts")),
                        (String) step.getOrDefault("reason", ""));
                case "bootstrap" -> {
                    List<RiskFill> fills = new ArrayList<>();
                    for (Object f : Json.array(step.get("fills"))) {
                        fills.add(parseFill(Json.object(f)));
                    }
                    eng.bootstrapPositions(fills, Json.asLong(step.get("ts")));
                }
                case "restore" -> restore(Json.asLong(step.get("ts")));
                default -> throw new IllegalStateException(
                        "step " + i + ": unknown step type " + kind);
            }
        }
    }

    /**
     * Replay once. With {@code cut >= 0} the engine is snapshotted and
     * restored ({@code ts} 0) after that step.
     */
    private static Run run(Map<String, Object> script, int cut, boolean check) {
        Runner runner = new Runner(script);
        List<Object> steps = Json.array(script.get("steps"));
        int mark = 0;
        for (int i = 0; i < steps.size(); i++) {
            runner.apply(i, Json.object(steps.get(i)), check);
            if (i == cut) {
                mark = runner.lineCount();
                runner.restore(0);
            }
        }
        return new Run(runner.audit(), mark, runner.snapshotText());
    }

    /** The audit's lines (LF only: a reason may contain U+2028). */
    private static List<String> lines(String audit) {
        List<String> out = new ArrayList<>(List.of(audit.split("\n", -1)));
        out.remove(out.size() - 1);
        return out;
    }

    private static String firstDiff(List<String> got, List<String> want) {
        for (int i = 0; i < Math.min(got.size(), want.size()); i++) {
            if (!got.get(i).equals(want.get(i))) {
                return "line " + i + ": got " + got.get(i) + " want " + want.get(i);
            }
        }
        return got.size() + " lines, want " + want.size();
    }

    /**
     * Snapshots are compared as documents: the Java engine prints doubles
     * with {@code Double.toString} (exact on round trip), the oracle with
     * the {@code serde_json} layout, so the bytes differ where the values
     * do not. Returns {@code null} when equal, else the first field that
     * differs.
     */
    private static String snapshotDiff(String got, String want) {
        if (got.isEmpty() || want.isEmpty()) {
            return got.equals(want) ? null : "one side has no snapshot";
        }
        Map<String, Object> g = Json.object(Json.parse(got));
        Map<String, Object> w = Json.object(Json.parse(want));
        if (g.equals(w)) {
            return null;
        }
        for (Map.Entry<String, Object> e : w.entrySet()) {
            if (!Objects.equals(e.getValue(), g.get(e.getKey()))) {
                String text = e.getKey() + ": got " + g.get(e.getKey()) + " want "
                        + e.getValue();
                return text.length() > 600 ? text.substring(0, 600) : text;
            }
        }
        return "unexpected fields " + g.keySet();
    }

    /** The full check of one script. */
    private static void verify(Case c) {
        Run main = run(c.script(), -1, true);
        List<String> full = lines(main.audit());
        if (!main.audit().equals(c.audit())) {
            throw new Divergence("audit differs: " + firstDiff(full, lines(c.audit())));
        }
        String diff = snapshotDiff(main.snapshot(), c.snapshot());
        if (diff != null) {
            throw new Divergence("final snapshot differs at " + diff);
        }
        for (Object cutValue : Json.array(c.script().get("cuts"))) {
            int cut = (int) Json.asLong(cutValue);
            Run r = run(c.script(), cut, true);
            List<String> got = lines(r.audit());
            int mark = r.mark();
            if (!got.get(mark).contains("\"rule_id\":\"STATE_RESTORED\"")) {
                throw new Divergence("cut " + cut + ": no STATE_RESTORED record");
            }
            if (!got.subList(0, mark).equals(full.subList(0, mark))
                    || !got.subList(mark + 1, got.size())
                            .equals(full.subList(mark, full.size()))) {
                throw new Divergence("cut " + cut
                        + ": the restored engine's audit tail differs");
            }
            diff = snapshotDiff(r.snapshot(), c.snapshot());
            if (diff != null) {
                throw new Divergence("cut " + cut
                        + ": the restored engine's final state differs at " + diff);
            }
        }
    }

    /** {@code verify}, with any exception turned into a reported divergence. */
    private static String verdict(Case c) {
        try {
            verify(c);
            return null;
        } catch (Divergence d) {
            return d.getMessage();
        } catch (RuntimeException e) {
            return "threw " + e;
        }
    }

    private static String oneLine(String text) {
        String flat = String.join(" ", text.trim().split("\\s+"));
        return flat.length() > 2000 ? flat.substring(0, 2000) : flat;
    }

    @Test
    public void fuzzCorpusReplaysByteForByte() {
        Path external = envDir("IAP_RISK_FUZZ_DIR");
        List<Case> corpus = loadCorpus(external == null ? CORPUS : external);
        long steps = 0;
        for (Case c : corpus) {
            steps += Json.array(c.script().get("steps")).size();
        }
        if (external == null) {
            assertTrue("the committed corpus has " + corpus.size() + " scripts",
                    corpus.size() >= 36);
            assertTrue("the committed corpus has " + steps + " steps", steps >= 3000);
        }
        long started = System.nanoTime();
        Map<String, String> verdicts = new LinkedHashMap<>();
        for (Case c : corpus) {
            verdicts.put(c.name(), verdict(c));
        }
        System.out.println("risk fuzz replay (java): " + corpus.size() + " scripts, "
                + steps + " steps in " + (System.nanoTime() - started) / 1_000_000
                + " ms");
        Path out = envDir("IAP_RISK_FUZZ_OUT");
        if (out != null) {
            StringBuilder report = new StringBuilder();
            try {
                Files.createDirectories(out);
            } catch (IOException e) {
                throw new IllegalStateException("cannot create " + out, e);
            }
            for (Case c : corpus) {
                String why = verdicts.get(c.name());
                report.append(c.name()).append(why == null ? "\tOK"
                        : "\tDIVERGED\t" + oneLine(why)).append('\n');
                Run produced;
                try {
                    produced = run(c.script(), -1, false);
                } catch (RuntimeException e) {
                    produced = new Run("", 0, "");
                }
                write(out.resolve(c.name() + ".java.audit.jsonl"), produced.audit());
                write(out.resolve(c.name() + ".java.snapshot.json"), produced.snapshot());
            }
            write(out.resolve("java.tsv"), report.toString());
            return;
        }
        List<String> failures = new ArrayList<>();
        for (Map.Entry<String, String> e : verdicts.entrySet()) {
            if (e.getValue() != null) {
                failures.add(e.getKey() + ": " + e.getValue());
            }
        }
        if (!failures.isEmpty()) {
            fail(failures.size() + " of " + corpus.size()
                    + " fuzz scripts diverge from the oracle:\n"
                    + String.join("\n", failures));
        }
    }

    private static boolean restoreRefused(Case c, Map<String, Object> snap) {
        try {
            RiskEngine.restore(RiskLimits.fromJson(effectiveConfig(c.script())),
                    RiskGoldenTest.instruments(c.script()), snap, 0);
            return false;
        } catch (RuntimeException refused) {
            return true;
        }
    }

    /**
     * A snapshot with any field missing or of the wrong type is refused (the
     * one optional field is {@code loss_override_global}: absent means no
     * override); a truncated document does not even parse.
     */
    @Test
    public void fuzzCorpusCorruptSnapshotsFailClosed() {
        int checked = 0;
        for (Case c : loadCorpus(CORPUS)) {
            if (c.snapshot().isEmpty()) {
                continue;
            }
            Map<String, Object> snap = Json.object(Json.parse(c.snapshot()));
            assertTrue(c.name(), !restoreRefused(c, snap));
            for (String key : snap.keySet()) {
                Map<String, Object> wrong = new LinkedHashMap<>(snap);
                wrong.put(key, "x");
                assertTrue(c.name() + ": " + key + " of the wrong type must be refused",
                        restoreRefused(c, wrong));
                if (!key.equals("loss_override_global")) {
                    Map<String, Object> missing = new LinkedHashMap<>(snap);
                    missing.remove(key);
                    assertTrue(c.name() + ": a snapshot without " + key
                            + " must be refused", restoreRefused(c, missing));
                }
                checked++;
            }
            String half = c.snapshot().substring(0, c.snapshot().length() / 2);
            boolean parsed;
            try {
                Json.parse(half);
                parsed = true;
            } catch (RuntimeException expected) {
                parsed = false;
            }
            assertTrue(c.name() + ": a truncated snapshot must not parse", !parsed);
        }
        assertTrue(checked + " snapshot fields checked", checked >= 30 * 16);
    }

    /**
     * NaN / Infinity never reach the JSON corpus; pin them here. The same
     * assertions live in the Rust and Python fuzz tests.
     */
    @Test
    public void nonFiniteInputsAreRejectedLikeTheOtherPorts() {
        final long t0 = 1_700_000_000_000_000_000L;
        Map<String, Object> doc = Json.object(com.iap.config.Json.parseFile(
                Paths.get("..", "configs", "risk", "risk.json")));
        TreeMap<Long, InstrumentRef> refs = new TreeMap<>();
        refs.put(1L, InstrumentRef.equity(0.01));
        RiskEngine eng = RiskEngine.fromConfig(doc, refs);
        eng.onMarket(1, 2450, 2452, t0);
        double[] bad = {Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY};
        String[] text = {"NaN", "inf", "-inf"};
        for (int k = 0; k < bad.length; k++) {
            RiskDecision d = eng.checkOrder(new OrderRequest(k + 1, 1, 0, 10, 2450,
                    OrderRequest.LIMIT, 1, "S1", bad[k], t0));
            assertEquals("MALFORMED_ORDER", d.ruleId());
            assertEquals("urgency must be in [0, 1]: " + text[k], d.reason());
        }
        String[][] scopes = {{"GLOBAL", ""}, {"STRATEGY", "S1"}};
        for (String[] scope : scopes) {
            for (double limit : bad) {
                boolean refused = false;
                try {
                    eng.overrideLossLimit(Scope.parse(scope[0]), scope[1], limit, t0,
                            "ops");
                } catch (IllegalArgumentException expected) {
                    refused = true;
                }
                assertTrue("a non-finite loss limit must be refused", refused);
            }
        }
        assertEquals("a refused override leaves no audit record", 3, eng.audit().size());
        assertEquals("ALLOW", eng.checkOrder(new OrderRequest(9, 1, 0, 10, 2450,
                OrderRequest.LIMIT, 1, "S1", 0.5, t0)).ruleId());
    }
}
