"""Golden replay of the risk differential-fuzz corpus
(``tests/golden/risk_fuzz/``, generated by
``python/tools/make_risk_fuzz_corpus.py``) — the Python side of the
three-language parity proof (Rust ``rust/risk/tests/golden_risk_fuzz.rs``,
Java ``RiskFuzzGoldenTest``).

Every script is replayed through ``iap.risk``: each order step's decision,
rule, severity, scope, scope id and reason must match, the audit JSONL and the
final snapshot must be byte-identical, and at every cut point a snapshot ->
restore -> continue run must produce the unbroken run's remaining output.
The Python engine is also the oracle that wrote the corpus, so this file
additionally pins that the committed bytes are what the generator produces
today (a stale corpus fails here and in CI's ``--check`` step).
"""

from __future__ import annotations

import copy
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
from iap.risk import RiskEngine, RiskLimits, instrument_refs_from_golden

TOOLS = Path(__file__).resolve().parents[1] / "tools"
sys.path.insert(0, str(TOOLS))

import make_risk_fuzz_corpus as corpus_tool  # noqa: E402
import risk_fuzz as rf  # noqa: E402


@pytest.fixture(scope="module")
def base() -> dict:
    return rf.load_base_config()


@pytest.fixture(scope="module")
def corpus(golden_dir: Path) -> list:
    loaded = rf.load_corpus(golden_dir / "risk_fuzz")
    assert loaded, "tests/golden/risk_fuzz is empty"
    return loaded


def test_fuzz_golden_corpus_shape(corpus):
    """Sized as documented: a few dozen scripts, thousands of steps, every
    step type, every configuration regime."""
    cov = rf.coverage(corpus)
    assert cov["scripts"] == len(corpus_tool.corpus_plan()) >= 36
    assert cov["steps"] >= 3000
    assert all(n > 0 for n in cov["step_types"].values()), cov["step_types"]
    assert {s["profile"] for s, _, _ in corpus} == set(rf.PROFILES)
    assert all(s["x-version"] == rf.SCRIPT_VERSION for s, _, _ in corpus)
    with_cuts = [s for s, _, _ in corpus if s["cuts"]]
    assert len(with_cuts) >= 30
    for script in with_cuts:
        assert all(0 <= c < len(script["steps"]) - 1 for c in script["cuts"])


def test_fuzz_golden_reaches_every_reason_branch(corpus):
    """Every rule id and every reason-string branch of the engine is reached,
    except the ones that are provably unreachable."""
    cov = rf.coverage(corpus)
    missed = [b for b in cov["branches_missed"] if b not in rf.UNREACHABLE]
    assert not missed, [rf.branch_label(b) for b in missed]
    assert set(cov["branches_missed"]) == set(rf.UNREACHABLE)


def test_fuzz_golden_replay_matches_byte_for_byte(corpus, base):
    for script, audit, snapshot in corpus:
        rf.verify_script(script, base, audit, snapshot)


def test_fuzz_golden_corpus_is_what_the_generator_produces(golden_dir):
    """The committed bytes equal a fresh generation (LF, no BOM, ASCII
    scripts): the corpus cannot go stale silently."""
    files, _ = corpus_tool.build(corpus_tool.corpus_plan())
    on_disk = {p.name: p.read_bytes() for p in (golden_dir / "risk_fuzz").iterdir()}
    assert sorted(on_disk) == sorted(files)
    for name, data in files.items():
        assert on_disk[name] == data, f"{name} is stale"
        assert b"\r" not in data, name
        if name.endswith(".json") and not name.endswith(".snapshot.json"):
            assert data.isascii(), name
    assert sum(len(b) for b in files.values()) < 3_000_000


def test_fuzz_golden_generation_does_not_depend_on_the_hash_seed():
    """No hash-ordered iteration anywhere in the generator: a different
    ``PYTHONHASHSEED`` regenerates the identical corpus."""
    for seed in ("1", "2718"):
        env = dict(os.environ, PYTHONHASHSEED=seed, PYTHONUTF8="1")
        done = subprocess.run(
            [sys.executable, str(TOOLS / "make_risk_fuzz_corpus.py"), "--check"],
            env=env,
            capture_output=True,
            text=True,
            check=False,
        )
        assert done.returncode == 0, done.stdout + done.stderr


def test_fuzz_golden_corrupt_snapshots_fail_closed(corpus, base):
    """A snapshot with any field missing or of the wrong type is refused (the
    one optional field is ``loss_override_global``: absent means no override);
    a truncated document does not even parse."""
    checked = 0
    for script, _, snapshot in corpus:
        if not snapshot:
            continue
        doc = rf.effective_config(script, base)
        limits = RiskLimits.from_json(doc)
        refs = instrument_refs_from_golden(script["instruments"])
        snap = json.loads(snapshot)
        RiskEngine.restore(limits, refs, snap, 0)
        for key in snap:
            wrong = copy.deepcopy(snap)
            wrong[key] = "x"
            with pytest.raises(ValueError):
                RiskEngine.restore(limits, refs, wrong, 0)
            if key != "loss_override_global":
                missing = copy.deepcopy(snap)
                del missing[key]
                with pytest.raises(ValueError):
                    RiskEngine.restore(limits, refs, missing, 0)
            checked += 1
        with pytest.raises(ValueError):
            json.loads(snapshot[: len(snapshot) // 2])
    assert checked >= 30 * 16
