"""Golden execution-replay fills (tests/golden/expected_replay_fills.json).

The pinned scenario (generated by the C++ reference via
cpp/tools/make_replay_fills_golden.cpp): events_eq_mbo.jsonl (instrument 1,
venue XV1, tick 0.01) worked by

  parent 1: VWAP BUY 400 over [t0+60s, t0+660s), 4 passive LIMIT slices
            joining the best bid  -> slice quantities {129, 71, 71, 129};
  parent 2: IS   SELL 600 over [t0+120s, t0+720s), 3 MARKET slices,
            risk_aversion 1.0    -> quantities {304, 184, 112}.

ticks / qty / ts / ids are compared EXACTLY; fee and impact_cost at the
1e-9 tolerance the C++ and Java golden tests use (they are in fact
bit-identical here, which the parity test at the bottom pins as well).
"""

from __future__ import annotations

import json
import math

import pytest

from iap.core.codec import read_jsonl
from iap.core.rng import SplitMix64
from iap.execution import (
    AlgoType,
    ExecConfig,
    ExecutionReplay,
    InstrumentSpec,
    Liquidity,
    ParentOrder,
    load_venues,
)

SEC = 1_000_000_000
TOL = 1e-9


def golden_config(configs_dir) -> ExecConfig:
    return ExecConfig(
        seed=20260829,
        impact_coeff_bps_per_pct_adv=2.0,
        venues=load_venues(configs_dir / "venues" / "venues.json"),
        instruments={1: InstrumentSpec(1, 0.01, 1.0, 38_000_000.0)},
    )


def golden_parents(t0: int):
    vwap = ParentOrder(
        parent_id=1, instrument_id=1, venue_id=1, side=0, qty=400,
        algo=AlgoType.VWAP, start_ts=t0 + 60 * SEC, end_ts=t0 + 660 * SEC,
        slices=4,
    )
    is_ = ParentOrder(
        parent_id=2, instrument_id=1, venue_id=1, side=1, qty=600,
        algo=AlgoType.IS, start_ts=t0 + 120 * SEC, end_ts=t0 + 720 * SEC,
        slices=3, risk_aversion=1.0,
    )
    return [vwap, is_]


@pytest.fixture(scope="module")
def golden(golden_dir):
    with open(golden_dir / "expected_replay_fills.json") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def events(golden_dir):
    return read_jsonl(golden_dir / "events_eq_mbo.jsonl")


@pytest.fixture(scope="module")
def configs_dir(golden_dir):
    return golden_dir.parents[1] / "configs"


def run_golden_scenario(events, configs_dir):
    replay = ExecutionReplay(
        golden_config(configs_dir), golden_parents(events[0].exchange_ts)
    )
    return replay.run(events), replay


def test_golden_exact_fill_list_matches(golden, events, configs_dir):
    assert golden["x-version"] == 2
    assert golden["seed"] == 20260829
    assert golden["t0"] == events[0].exchange_ts
    res, _ = run_golden_scenario(events, configs_dir)
    assert res.events_processed == golden["events_processed"]
    want_fills = golden["fills"]
    # 7 since 2026-09-20: passive fills are bounded by the observed trade
    # volume and share one liquidity pool, so the old single 129-share fill
    # is now the 100 the tape actually showed plus a later 29.
    assert len(res.fills) == len(want_fills) == 7
    for i, (got, want) in enumerate(zip(res.fills, want_fills)):
        what = f"fill {i + 1}"
        assert got.fill_id == want["fill_id"], what
        assert got.order_id == want["order_id"], what
        assert got.parent_id == want["parent_id"], what
        assert got.instrument_id == want["instrument_id"], what
        assert got.venue_id == want["venue_id"], what
        assert got.side == want["side"], what
        assert got.price_ticks == want["price_ticks"], what  # exact
        assert got.qty == want["qty"], what  # exact
        assert got.ts == want["ts"], what  # exact
        assert got.liquidity.name == want["liquidity"], what
        assert abs(got.fee - want["fee"]) <= TOL, what
        assert abs(got.impact_cost - want["impact_cost"]) <= TOL, what
    for pid in ("1", "2"):
        want = golden["parents"][pid]
        got = res.parents[int(pid)]
        assert got.filled_qty == want["filled_qty"]
        assert got.unfilled_qty == want["unfilled_qty"]
        assert got.children == want["children"]
        for key in ("notional", "avg_price", "fees", "rebates", "impact", "total_cost"):
            assert abs(getattr(got, key) - want[key]) <= TOL, (pid, key)
        # Identity: total_cost = fees - rebates + impact.
        assert abs(got.total_cost - (got.fees - got.rebates + got.impact)) <= 1e-12


def test_golden_rows_are_bit_identical_to_the_cpp_reference(golden, events, configs_dir):
    """Stronger than 1e-9: the C++ %.17g doubles round-trip to our doubles."""
    res, _ = run_golden_scenario(events, configs_dir)
    for got, want in zip(res.fills, golden["fills"]):
        row = got.to_dict()
        assert row == {**want, "impact_cost": float(want["impact_cost"])}
        assert row["fee"] == want["fee"]
        assert row["impact_cost"] == want["impact_cost"]
    for pid, want in golden["parents"].items():
        got = res.parents[int(pid)].to_dict()
        assert list(got) == list(want)
        for key, value in want.items():
            assert got[key] == value, (pid, key)


def test_golden_hand_traced_first_fills(events, configs_dir):
    res, _ = run_golden_scenario(events, configs_dir)
    assert len(res.fills) >= 3
    # Jitter draws from SplitMix64(20260829) in submission order (order 1 =
    # VWAP slice 0 was submitted first: draw #1).
    rng = SplitMix64(20260829)
    j1 = rng.below(50_000 + 1)
    j2 = rng.below(50_000 + 1)
    assert j1 == 21675
    assert j2 == 14614
    # Fill 1: IS slice 0 — aggressive, stamped with its arrival_ts.
    f1 = res.fills[0]
    assert f1.order_id == 2 and f1.parent_id == 2
    assert f1.qty == 304  # IS slice quantities {304, 184, 112}
    assert f1.price_ticks == 2451  # pre-event best bid 2451 x 600
    assert f1.liquidity == Liquidity.TAKER
    decision2 = 1787578329585937884  # event 74
    assert f1.ts == decision2 + 350_000 + j2
    assert f1.fee == 0.003 * 304
    impact_bps = 2.0 * (304.0 / 38_000_000.0 * 100.0)
    assert math.isclose(f1.impact_cost, impact_bps * 1e-4 * (304.0 * 2451 * 0.01), abs_tol=1e-15)
    # Fill 2: VWAP slice 0 — passive trade-through fill at our own level,
    # capped at the 100 shares event 98 actually traded (slice qty 129).
    f2 = res.fills[1]
    assert f2.order_id == 1 and f2.parent_id == 1
    assert f2.qty == 100  # bounded by the observed volume
    assert f2.price_ticks == 2449  # best bid at the slice-0 decision
    assert f2.liquidity == Liquidity.MAKER
    assert f2.ts == 1787578386181246977  # event 98 (trade-through)
    assert f2.fee == -0.002 * 100
    decision1 = 1787578263509538609  # event 48
    assert decision1 + 350_000 + j1 == 1787578263509910284
    assert f2.ts > decision1 + 350_000 + j1
    # Fill 3: the slice-0 residual, taken by the next trade-through
    # (event 103, a 100-share bid EXECUTE at 2448).
    f3 = res.fills[2]
    assert f3.order_id == 1
    assert f3.qty == 29  # 100 + 29 = the 129-share slice
    assert f3.price_ticks == 2449
    assert f3.liquidity == Liquidity.MAKER
    assert f3.ts == 1787578395624588691  # event 103
    assert f3.fee == -0.002 * 29


def test_golden_deterministic_rerun(events, configs_dir):
    a, _ = run_golden_scenario(events, configs_dir)
    b, _ = run_golden_scenario(events, configs_dir)
    assert [f.to_dict() for f in a.fills] == [f.to_dict() for f in b.fills]
    assert {k: v.to_dict() for k, v in a.parents.items()} == {
        k: v.to_dict() for k, v in b.parents.items()
    }


def test_golden_both_parents_complete_with_mixed_liquidity(events, configs_dir):
    res, replay = run_golden_scenario(events, configs_dir)
    maker_qty = taker_qty = 0
    for f in res.fills:
        if f.liquidity == Liquidity.MAKER:
            assert f.parent_id == 1
            assert f.impact_cost == 0.0  # passive fills: no impact
            maker_qty += f.qty
        else:
            assert f.parent_id == 2
            assert f.impact_cost > 0.0
            taker_qty += f.qty
    assert maker_qty == 329
    assert taker_qty == 600
    assert res.parents[1].unfilled_qty == 71
    # Every attributed fill lies inside its parent's window (pinned) and
    # the slice-2 VWAP child expired at end_ts (golden v2).
    t0 = events[0].exchange_ts
    for f in res.fills:
        end = t0 + (660 if f.parent_id == 1 else 720) * SEC
        assert f.ts <= end
    assert replay.simulator.counters.expired_orders == 1


def test_golden_one_shot_run_enforced(events, configs_dir):
    replay = ExecutionReplay(
        golden_config(configs_dir), golden_parents(events[0].exchange_ts)
    )
    replay.run(events)
    with pytest.raises(RuntimeError):
        replay.run(events)
